### ISSUE TITLE
Some issues in Ubuntu 15.04

### ISSUE THREAD

**Issue by gabdub** [Simmesimme/Gnome-Pie#100]
In a fresh Ubuntu 15.04 install, gnome-pie print the following warnings in the console:

`[MESSAGE] Welcome to Gnome-Pie 0.6.1!`
`[MESSAGE] Loading Pies from "/home/gabriel/.config/gnome-pie/pies.conf".`
`(gnome-pie:20205): GLib-GObject-WARNING **: invalid (NULL) pointer instance`
`(gnome-pie:20205): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed`
`[MESSAGE] Started happily...`
`(gnome-pie:20205): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed`
`(gnome-pie:20205): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed`

**Comment by Simmesimme** [comment]
For me, this does not happen with the latest development branch! Does it for you?

**Comment by gabdub** [comment]
Yes, I pulled the code from the development branch, rebuilt it and got the same warnings.
All seems to be working, thought.
I also noticed that all the strings were in English the first time I installed from the PPA, but after rebuilding that issue was solved. 
I'll re check it when at home.

**Comment by Simmesimme** [comment]
And be sure not to have it installed system wide while running a local version... It will try to load ui-files which belong to the wrong version. Maybe this should be fixed...

**Comment by gabdub** [comment]
All is right now, thanks.
