### ISSUE TITLE
文件夹书签中看不到内容

### ISSUE THREAD

**Issue by linux0ne** [Simmesimme/Gnome-Pie#103]
1、我的系统是ubuntu 14.04 LTS 32bit，unity 桌面，现在已更新的到最新。
2、安装本软件的最新版本后，设置ctrl + alt + a为快捷键，但是在按下后，发现书签功能并不好使。
3、在我的文件管理器中，书签位置已经有很多内容了。

**Comment by Simmesimme** [comment]
我需要更多的信息。我们可以用英语讨论这个问题？
