### ISSUE TITLE
Not Bound - only able to add  1 "unbound Pie"

### ISSUE THREAD

**Issue by cleder** [Simmesimme/Gnome-Pie#105]
I use GP mainly as a way to organize my launcher (great for this). I do not need hot keys for these actions. To save the Pie I need to assign a hot key to it.

It would be nice if i could add more than one Pie without a hotkey

**Comment by gabdub** [comment]
Hi, this was solved in 0.6.1 version.
What version are you running?

**Comment by gabdub** [comment]
Actually, there is a problem: you can only have one pie without a hot key.
Thanks for the report!

**Comment by cleder** [comment]
version 0.6.2
