### ISSUE TITLE
no panel/tray icon in GNOME Shell 3.16

### ISSUE THREAD

**Issue by corebots** [Simmesimme/Gnome-Pie#107]
After launching Gnome-Pie with 'Display panel icon' option selected, only an empty space is added to the tray/panel of GNOME Shell (3.16.1 and 3.16.2) - no icon is displayed (while space remains clickable)

**Comment by Simmesimme** [comment]
Thanks for the report! How did you install Gnome-Pie? Do you have a local version or have you installed it system-wide?

**Comment by gabdub** [comment]
I installed a fresh Arch+Gnome 3.16+gnome-pie from the repositories in a VM and confirm the bug.
The programm is installed in /usr/bin/ and the resources are in /usr/share/gnome-pie/themes and /usr/share/gnome-pie/ui.

This warnings appears in the terminal:
'[MESSAGE] Welcome to Gnome-Pie 0.6.2!'
'[MESSAGE] Loading Pies from "/home/desa33/.config/gnome-pie/pies.conf".'
'[WARNING] Failed to find file ".gtk-bookmarks"!'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkAlignment:top-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkAlignment:bottom-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkAlignment:right-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkButton:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkMisc:ypad is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'(gnome-pie:928): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.'
'[MESSAGE] Started happily...'

**Comment by corebots** [comment]
it's been a few weeks since i've installed it and am not sure anymore, how can I check? sorry I'm not that advanced with linux. the executable gnome-pie sits under /usr/local/bin and the config and themes under /usr/local/share/gnome-pie so I guess it's a local version?

**Comment by Simmesimme** [comment]
Gnome is behaving kind of strange here. I implemented a workaround (528443135a180b098dd1ce913f98369a1c4c43c0) which should fix this problem for now. You may compile this yourself to test it or wait for the next release!

**Comment by corebots** [comment]
Thank you, icon is visible now ! :)
