### ISSUE TITLE
Select a Slice by typing it's name

### ISSUE THREAD

**Issue by Kuxe** [Simmesimme/Gnome-Pie#108]
Currently I select pies with arrows or alt+integer. Another way of selecting a slice within the current pie would be to type the name of the slice. For example, if I have a pie with some applications:

Opera
Steam
Atom
Spotify

Typing "o" selects opera. Typing "a" selects Atom.. "st" selects Steam and so forth.. Perhaps fading slices that doesn't match the search-string? Maybe fuzzy-search? Anyhow, some select-by-type feature would be really nice :)

**Comment by blendi-93** [comment]
yea nice idea

**Comment by Simmesimme** [comment]
Thanks for this suggestion! I have implemented such a feature in dddc615f1ea3b790aa86002aa0e266338bd9aa04. It will be part of the next version! (If you do not want to wait, [compile Gnome-Pie from source](http://simmesimme.github.io/gnome-pie.html#toc5)! You'll have to use the develop branch)
