### ISSUE TITLE
Black background issues

### ISSUE THREAD

**Issue by thunderbirdtr** [Simmesimme/Gnome-Pie#110]
Hello ; I just installed globally and I don't have systray icon + I have huge "black background problem ; and here is the picture ; 

![screenshot from 2015-06-07 22-13-54](https://cloud.githubusercontent.com/assets/1688848/8025569/cea8ebbe-0d62-11e5-906a-49690f79ecaf.png)

**Comment by Simmesimme** [comment]
Hi! 

The missing system tray icon will be fixed in the next version. What do you mean with "black background problem"? I see some strange squares in the center of your screenshot (but they may be part of your wallpaper). The black background behind the Slice's labels are part of this theme (and should be redesigned, I think).

**Comment by aimnadze** [comment]
I'm experiencing a similar issue. When I open Gnome Pie with let's say Ctrl+Shift+A the backgrounds appear black. However when I take a screenshot and paste it in GIMP the black rectangles appears as transparent. This is the screenshot exported from GIMP http://ogg.ge/gnome-pie-black.png

I'm using 0.5.5 as distributed in Debian Jessie channel. Unfortunately I couldn't compile or install the latest version.

**Comment by Simmesimme** [comment]
Well, 0.5.5 is really old; 0.5.6 fixed some transparency issues eleven months ago (http://simmesimme.github.io/news/2015/01/14/gnome-pie-056/) ...

Why did you fail to [compile the most recent version](http://simmesimme.github.io/gnome-pie.html#toc5)? Maybe I can help you?

**Comment by aimnadze** [comment]
I've uninstalled 0.5.5 version.
This is the error I'm getting on running `./make.sh`:
```
error: Package `libbamf3' not found in specified Vala API directories or GObject-Introspection GIR directories
```

These are the packeges I have on my computer:
* `libbamf3-0` version `0.2.118-1`
* `libbamf3-dev` version `0.2.118-1`

Maybe they're incompatible?!

**Comment by Simmesimme** [comment]
Just have a look at issue #127! I hope this helps!

**Comment by Simmesimme** [comment]
Please re-open if this is still an issue!
