### ISSUE TITLE
Transparency issue

### ISSUE THREAD

**Issue by dstarina** [Simmesimme/Gnome-Pie#111]
Hi,

I'm using Fedora 22 with Gnome and I get a black square when the launcher opens. Love the Gnome Pie, but this makes it rather ugly :)

Also, printscreen stops working when it is active, otherwise I would post a picture of the problem ...

Best regards

**Comment by Simmesimme** [comment]
Hi!

What version of Gnome-Pie are you using? For me it works as supposed with Gnome. But this has been a bug some months ago...

FYI: You can capture a screenshot with a terminal command. Just enter the command below; it will make a screenshot after ten seconds. Just open Gnome-Pie before!

`gnome-screenshot --delay 10`

**Comment by dstarina** [comment]
Hi,

I'm using the one from Fedora repository. Should I try building and
installing from source?



This is the screenshot:


Best regards,
David
​
​

**Comment by Simmesimme** [comment]
It would be great if you tried to compile it from source!

**Comment by dstarina** [comment]
Is there any manual for installing it on Fedora? I only found the manual
for Ubuntu - is there a list of dependencies I need for Fedora?

Best regards,
David

**Comment by Simmesimme** [comment]
I recently added the fedora dependencies list to that short installation manual:

http://simmesimme.github.io/gnome-pie.html#toc5

Hope this helps!

**Comment by dstarina** [comment]
Hi,


This works. Thank you!

On Fri, Aug 14, 2015 at 11:13 AM, Simon Schneegans <notifications@github.com
