### ISSUE TITLE
Doesn't work on Wayland

### ISSUE THREAD

**Issue by kaslusimoes** [Simmesimme/Gnome-Pie#112]
First of all, thank you for this simple but really effective and beatiful application launcher.
I've tried to run `gnome-pie` on Wayland but it just exited with a segafult.

I'm using an Arch Linux 64-bit machine and [gnome-pie](https://aur4.archlinux.org/packages/gnome-pie-git/) as of commit 682d3d3

```
(gnome-pie:8271): Gtk-WARNING **: Error setting gtk-xft-antialias in /home/kaslu/.config/gtk-3.0/settings.ini: Key file contains key 'gtk-xft-antialias' in group 'Settings' which has a value that cannot be interpreted.

(gnome-pie:8271): Gtk-WARNING **: Error setting gtk-xft-hinting in /home/kaslu/.config/gtk-3.0/settings.ini: Key file contains key 'gtk-xft-hinting' in group 'Settings' which has a value that cannot be interpreted.
[MESSAGE] Welcome to Gnome-Pie 0.6.2!
[MESSAGE] Loading Pies from "/home/kaslu/.config/gnome-pie/pies.conf".
Segmentation fault (core dumped)
```

On this same machine of mine, I've run `gnome-pie` on XOrg naturally:

```
(gnome-pie:7288): Gtk-WARNING **: Error setting gtk-xft-antialias in /home/kaslu/.config/gtk-3.0/settings.ini: Key file contains key 'gtk-xft-antialias' in group 'Settings' which has a value that cannot be interpreted.

(gnome-pie:7288): Gtk-WARNING **: Error setting gtk-xft-hinting in /home/kaslu/.config/gtk-3.0/settings.ini: Key file contains key 'gtk-xft-hinting' in group 'Settings' which has a value that cannot be interpreted.
[MESSAGE] Welcome to Gnome-Pie 0.6.2!
[MESSAGE] Loading Pies from "/home/kaslu/.config/gnome-pie/pies.conf".

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkAlignment:top-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkAlignment:bottom-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkAlignment:right-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkButton:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkMisc:ypad is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.

(gnome-pie:7288): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
[MESSAGE] Started happily...
```

**Comment by kaslusimoes** [comment]
Sorry for the bad english, I'm not a native speaker

**Comment by Simmesimme** [comment]
Hi!

Thanks for the report. Could you please launch Gnome-Pie with gdb and post the backtrace? This would be helpful!

**Comment by kaslusimoes** [comment]
I'm not sure how I'm supposed to do that.
Should I compile with debug flags enabled and run `gdb gnome-pie`?
Could you give me further directions?

**Comment by kaslusimoes** [comment]
I'm compiling as specified on this [PKGBUILD](https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gnome-pie-git)

**Comment by Simmesimme** [comment]
It should be sufficient to run 

`gdb gnome-pie`

Then press `r`, wait until Gnome-Pie has crashed and then press `bt`. This should print the backtrace!

**Comment by kaslusimoes** [comment]
Easier than I thought :sweat_smile:

```
Reading symbols from gnome-pie...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/gnome-pie 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

(gnome-pie:28717): Gtk-WARNING **: Error setting gtk-xft-antialias in /home/kaslu/.config/gtk-3.0/settings.ini: Key file contains key 'gtk-xft-antialias' in group 'Settings' which has a value that cannot be interpreted.

(gnome-pie:28717): Gtk-WARNING **: Error setting gtk-xft-hinting in /home/kaslu/.config/gtk-3.0/settings.ini: Key file contains key 'gtk-xft-hinting' in group 'Settings' which has a value that cannot be interpreted.
[MESSAGE] Welcome to Gnome-Pie 0.6.3!
[MESSAGE] Loading Pies from "/home/kaslu/.config/gnome-pie/pies.conf".
[New Thread 0x7fffeb70e700 (LWP 28722)]
[New Thread 0x7fffebf0f700 (LWP 28721)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff523180c in XGrabKey () from /usr/lib/libX11.so.6
(gdb) bt
#0  0x00007ffff523180c in XGrabKey () from /usr/lib/libX11.so.6
#1  0x00000000004276ca in gnome_pie_binding_manager_bind ()
#2  0x000000000043cc18 in gnome_pie_pie_manager_create_persistent_pie ()
#3  0x000000000043e5b1 in gnome_pie_pies_parse_pie ()
#4  0x000000000043e9a1 in gnome_pie_pies_load ()
#5  0x000000000043c0e4 in gnome_pie_pie_manager_init ()
#6  0x0000000000419d43 in gnome_pie_deamon_construct ()
#7  0x0000000000419e03 in gnome_pie_deamon_main ()
#8  0x00007ffff470c790 in __libc_start_main () from /usr/lib/libc.so.6
#9  0x00000000004194d9 in _start ()
(gdb) 
```

**Comment by Simmesimme** [comment]
Okay. There are multiple calls to libX11 in Gnome-Pie, which obviously won't work with Wayland. I'll have to try to replace them with GTK methods. But I doubt that this will be easy.

I never used Wayland; is there a distro with which it's easy to get it up and running in a virtual machine? What are you using?

**Comment by kaslusimoes** [comment]
I'm using Arch Linux but I guess the newest Fedora works out of the box with Wayland (just changing the login option on GDM)

**Comment by Simmesimme** [comment]
Ok. I'll look into it!

**Comment by simonbcn** [comment]
Same problem on Arch Linux too with Gnome Shell 3.22

**Comment by pedrofleck** [comment]
Same problem here. And Gnome 3.22 (and Fedora 25 that will be released next month) now uses Wayland by default.

**Comment by RicardoEPRodrigues** [comment]
I have the same problem on Ubuntu GNOME. It's a good distro to test this out. Comes with both X11 and Wayland and will become the default distro for Ubuntu. (Unity is dead)

I can test it out on my system if you want.

**Comment by Simmesimme** [comment]
Yeah, I already had a look at this issue, but it seems to be a rather severe one. The segfault arises when Gnome-Pie tries to register the key bindings. 

In Wayland apps are much more isolated - as far as I can tell it is impossible to intercept any input events. Therefore it will be impossible to support the *deferred activation* and the binding of Pies to mouse buttons. Furthermore I am not sure if I can capture the input somehow once a Pie is opened. Maybe a transparent fullscreen window? But then maybe docks which are set to auto-hide will disappear...

If anyone has more knowledge here, please feel free to discuss the issue!

**Comment by Simmesimme** [comment]
I pushed several commits today which provide very basic Wayland support:
* Gnome-Pie does not crash anymore when started on Wayland
* There are several limitations on Wayland:
  * No key bindings. Pies have to be opened with the command line option --open "Pie-ID". You can for example add system shortcuts in the keyboard settings of your desktop which execute this command when issued.
  * Consequently there is no support for deferred activation and no turbo activation.
  * The mouse pointer cannot be warped to the center of the Pie.
  * For now the Pies can only be opened in the center of your screen. This is because I have no idea how it is possible to get the pointer position before it is moved by the user. I feel like it may be impossible. Therefore I cannot know where the Pie should open.
  * Since input capturing is impossible, I have to open a fullscreen window. This makes the whole thing much slower and may lead to unwanted side effects sich as auto-hiding panels.
  * The WindowListSliceGroup (Alt-Tab) is disabled for it uses wnck which is X11 specific.

Hopefully this can be improved in future, however a lot of security decisions have been made during the development of Wayland which make applications like Gnome-Pie basically impossible.
