### ISSUE TITLE
The indicator icon is lost in Ubuntu 14.04 in 0.6.3 version

### ISSUE THREAD

**Issue by gabdub** [Simmesimme/Gnome-Pie#113]
Hi Simon!

After updating to 0.6.3 version in Ubuntu 14.04, the indicator icon changed into a question mark.

I found at indicator.vala @ line 87 that the icon is tried to be loaded from the "resources" directory (that didn't exist in my pc).
It might be a regression from commit (force full path for appindicator icon) 528443135a180b098dd1ce913f98369a1c4c43c0.

I manually copied "gnome-pie-symbolic.svg" to /usr/bin/resources and the icon was back.
I also recompile the code from source and the same happened: I have to copy the icon to /usr/local/bin/resources to solve the issue ("make install" put the icon in "hicolor" icon directory).

Best regards,
Gabriel

**Comment by Simmesimme** [comment]
Oh, I see. The icon was in this directory on my system due to previous tests. I'll fix this asap. Thank you!

**Comment by Simmesimme** [comment]
As of commit e7b62fec0166fae5bb433c78c7d4237c81f592e4 it should work again. Can you confirm this?

I'm wondering whether Gnome-Pie should have a status icon in future. Gtk.StatusIcon is deprecated (https://bugzilla.gnome.org/show_bug.cgi?id=734826), and Gnome Shell will have no message tray at all. AppIndicators are Ubuntu-only. This fragmentation is aweful...

**Comment by gabdub** [comment]
Yes, now works again!
BTW, I'm using Numix-circle icons and the Numix version of the icon has return to the notification area.
---
You are write about fragmentation. One of the biggest problems I see with having so many desktops in Linux.
I once added a context menu for the pies in the launcher (to edit that pie directly) and came across this bug: https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/1242255
so I removed it. Unity is going to be completely replaced with version 8 so no much love is going to version 7....
