### ISSUE TITLE
[featurerequest] y and x keys for icons

### ISSUE THREAD

**Issue by blendi-93** [Simmesimme/Gnome-Pie#115]
as in the head i would love to see x and y keys for icons so i can create something like this:

![my nice pie](http://i.imgur.com/7QWnRIc.png)

**Comment by Simmesimme** [comment]
I'm not totally sure what you are requesting. Do you mean an option for the themes? Similar as the captions can be positioned?

**Comment by blendi-93** [comment]
y i want to move the icons and mby images like the text (but on both axes).

**Comment by Simmesimme** [comment]
Implemented in 577bbb87153a1346410256fdf47b1caaa6109e01. It will be in the next release, which will come soon!

**Comment by blendi-93** [comment]
that was fast, thx now i have my (awesome) theme:
![2015-08-09-132419_1600x900_scrot](https://cloud.githubusercontent.com/assets/4957651/9154620/570cad48-3e9a-11e5-846e-e89860360379.png)

heres the source if u want it ofc ;)
https://transfer.sh/14cxej/tiny-text.tar.gz

again thx (need gnome-pie as applauncher/switcher on my tablet)
