### ISSUE TITLE
No support for svg images.

### ISSUE THREAD

**Issue by AnthonyMazelin** [Simmesimme/Gnome-Pie#118]
After compiling the latest(0.6.5) Gnome-pie, changing themes has no affect. Instead, it shows error messages like 
````
[MESSAGE] Error loading image file: Couldn't recognize the image file format for file '/usr/local/share/gnome-pie/themes/o-pie/arrow.svg'.
```

**Comment by Simmesimme** [comment]
Have you checked that the file is actually there? Maybe it got damaged somehow? For me it's working flawlessly. What distro / wm are you using?

**Comment by AnthonyMazelin** [comment]
Closing bug, problem with my gtk installation.
