### ISSUE TITLE
Opensuse 13.2

### ISSUE THREAD

**Issue by iomari** [Simmesimme/Gnome-Pie#122]
After installing all the dependencies with no problems,
the compilation bombs at the end with:
[ 78%] Building C object src/CMakeFiles/gnome-pie.dir/utilities/focusGrabber.c.o
[ 80%] Building C object src/CMakeFiles/gnome-pie.dir/utilities/animatedValue.c.o
[ 81%] Building C object src/CMakeFiles/gnome-pie.dir/renderers/sliceRenderer.c.o
[ 83%] Building C object src/CMakeFiles/gnome-pie.dir/renderers/pieWindow.c.o
[ 84%] Building C object src/CMakeFiles/gnome-pie.dir/renderers/centerRenderer.c.o
[ 86%] Building C object src/CMakeFiles/gnome-pie.dir/renderers/pieRenderer.c.o
[ 87%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/menuGroup.c.o
[ 89%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/actionGroup.c.o
[ 90%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/workspaceWindowListGroup.c.o
[ 92%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/sessionGroup.c.o
[ 93%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/devicesGroup.c.o
[ 95%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/groupRegistry.c.o
[ 96%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/windowListGroup.c.o
[ 98%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/bookmarkGroup.c.o
[100%] Building C object src/CMakeFiles/gnome-pie.dir/actionGroups/clipboardGroup.c.o
Linking C executable ../../gnome-pie
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgdk-3.so: undefined reference to `cairo_surface_set_device_scale'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgtk-3.so: undefined reference to`cairo_surface_get_device_scale'
collect2: error: ld returned 1 exit status
src/CMakeFiles/gnome-pie.dir/build.make:1860: recipe for target '../gnome-pie' failed
make[2]: **\* [../gnome-pie] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/CMakeFiles/gnome-pie.dir/all' failed
make[1]: **\* [src/CMakeFiles/gnome-pie.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

How can I rectify this?

**Comment by Simmesimme** [comment]
Hi!

Thanks for the report! Are you using Gnome on openSuse? Else you're likely to run into other problems when this one is solved :)

I have not much experience with openSuse and it refuses to run in Virtualbox for some reason -- but I checked google and run into this discussion (arch-related but may help nevertheless): https://bbs.archlinux.org/viewtopic.php?id=188591

Can something similar work for you? If not we have to investigate further...

**Comment by Simmesimme** [comment]
If this is still an issue, please re-open!
