### ISSUE TITLE
Feature: Assign automatic key shortcut to each slice

### ISSUE THREAD

**Issue by computaholic** [Simmesimme/Gnome-Pie#123]
Hi,

So my problem is, that in order to invoke special pies, you need two hands on the keyboard. However, navigation between slices on the keyboard is poor.

What I would like to see:

if a pie comes up, there should be a letter assigned to each slice, which should be shown next to each slice. Pressing that key would then activate the slice.

Example

- Alt+Ctrl+H for a list of all windows
- Each window has a key shortcut assigned and shown next to the slice
- press e.g. k for window k.
- no mouse needed

It should be optional to use the key mapping feature.

Hope that was not too confusing.

**Comment by Simmesimme** [comment]
Hi,

I think what you're asking for actually exists already. You can either start typing the name of the desired item to select it, or if the checkbox in the settings menu I marked below is unchecked, each item has its own hotkey which is show when you hold down the ALT key while a Pie is open.

![settings](https://cloud.githubusercontent.com/assets/829942/10285332/52fe7976-6b80-11e5-9228-e997ef494a60.jpg)

Is that what you're asking for?

BTW, the default hotkeys are just examples. You should change them to something you can actually press with one hand :)

**Comment by computaholic** [comment]
That's it:) Thanks for your help!!

BTW: Your screenshot looks really nice. Is that Ubuntu? What Desktop and theme do you use? (Sorry for off topic:)

**Comment by Simmesimme** [comment]
Great :)

It's [elementary OS](https://elementary.io/) (which is based on Ubuntu 14.04) with [Numix Circle Icons](https://github.com/numixproject/numix-icon-theme-circle) and the [Arc GTK theme](https://github.com/horst3180/Arc-theme).

Have fun!
