### ISSUE TITLE
"gnome-pie" bash command now opens a pie directly instead of Preference Menu since 0.6.7

### ISSUE THREAD

**Issue by washburn94** [Simmesimme/Gnome-Pie#124]
Hi,

I'm on Archlinux and since I started using the new version 0.6.7, but I can't access the preference menu anymore. Typing gnome-pie in a terminal do the same as if I would type gnome-pie -o 651. Any clues?

Marc-Antoine

**Comment by Simmesimme** [comment]
Hi! Thanks for reporting the issue. I'll fix this asap. A temporary workaround should be:

* Quit Gnome-Pie
* Launch it again (simply with `gnome-pie`; not with a pie id)
* Type `gnome-pie` again. The settings menu should appear!

The bug causes Gnome-Pie to remember what it was supposed to do when it was started for the first time. So your buggy behavior should be reproducible with:

* Quit Gnome-Pie
* Launch it again with an id `gnome-pie -o 651`
* Type `gnome-pie` again. The pie will appear!

Thanks again; there will be a 0.6.8 soon I suppose :)

**Comment by washburn94** [comment]
Thanks, it works! (I love this project btw, keep up the good work! :) )
