### ISSUE TITLE
Display clock (time) inside center of pie when inactive [FEATURE REQUEST]

### ISSUE THREAD

**Issue by washburn94** [Simmesimme/Gnome-Pie#125]
The title says everything. It would be nice, isn't it ? :)

**Comment by Simmesimme** [comment]
Well, that's a funny idea, however I'm not sure about the implementation. A digital clock would be boring; an analog one would be very funny. Maybe it is possible to add this as a theme option... let me think about this :)

**Comment by Simmesimme** [comment]
It's already taking shape. Now I need to design some themes using this new feature. Thanks for that a wesome idea!

![clock](https://cloud.githubusercontent.com/assets/829942/10319404/04e0e7f6-6c66-11e5-96a0-120d00c6fa27.jpg)

**Comment by washburn94** [comment]
This is looking good. I'm looking forward to use them ! Cool :D

**Comment by Simmesimme** [comment]
Done. 

http://simmesimme.github.io/news/2015/10/06/gnome-pie-068/

Have fun! (The PPA should be updated in some minutes)
