### ISSUE TITLE
Fail to build on Debian jessie

### ISSUE THREAD

**Issue by nardev** [Simmesimme/Gnome-Pie#127]
When i try to build this under Debian i get libbamf3 missing error. however, i have it installed.

Maybe some paths???

---
root@host:/home/user/Desktop/Gnome-Pie# ./make.sh 
bg/ 101 translated messages, 55 untranslated messages.
de/ 156 translated messages.
es/ 153 translated messages, 3 untranslated messages.
fr/ 153 translated messages, 3 untranslated messages.
it/ 47 translated messages, 19 fuzzy translations, 90 untranslated messages.
ko/ 99 translated messages, 1 fuzzy translation, 56 untranslated messages.
lt/ 153 translated messages, 3 untranslated messages.
pt_BR/ 101 translated messages, 55 untranslated messages.
ru/ 79 translated messages, 21 fuzzy translations, 56 untranslated messages.
zh_CN/ 101 translated messages, 55 untranslated messages.
mkdir: cannot create directory ‘build’: File exists
-- checking for a minimum Vala version of 0.22.0
--   found Vala, version 0.26.1

Summary:
  EXECUTABLE_OUTPUT_PATH = /home/user/Desktop/Gnome-Pie
  VALA_EXECUTABLE = /usr/bin/valac
Libs:
  GTK3_LIBRARIES = gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
  CAIRO_LIBRARIES = cairo
  GEE_LIBRARIES = gee-0.8;gobject-2.0;glib-2.0
  INDICATOR_LIBRARIES = 
  INDICATOR3_LIBRARIES = appindicator3;dbusmenu-glib;gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
  XML_LIBRARIES = xml2
  XTST_LIBRARIES = Xtst
  GMENU_LIBRARIES = 
  GMENU3_LIBRARIES = gnome-menu-3;gio-2.0;gobject-2.0;glib-2.0
  X11_LIBRARIES = X11
  BAMF_LIBRARIES = bamf3;wnck-3;gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
  WNCK_LIBRARIES = wnck-3;gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
  ARCHIVE_LIBRARIES = /usr/lib/x86_64-linux-gnu/libarchive.so

-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Desktop/Gnome-Pie/build
[  1%] Generating daemon.c, pies/pie.c, pies/pieManager.c, pies/load.c, pies/defaultConfig.c, pies/save.c, actionGroups/groupRegistry.c, actionGroups/bookmarkGroup.c, actionGroups/clipboardGroup.c, actionGroups/windowListGroup.c, actionGroups/actionGroup.c, actionGroups/sessionGroup.c, actionGroups/devicesGroup.c, actionGroups/menuGroup.c, utilities/bindingManager.c, utilities/paths.c, utilities/animatedValue.c, utilities/key.c, utilities/logger.c, utilities/archiveReader.c, utilities/focusGrabber.c, utilities/config.c, utilities/archiveWriter.c, utilities/trigger.c, utilities/color.c, images/image.c, images/renderedText.c, images/icon.c, images/themedIcon.c, actions/sigAction.c, actions/actionRegistry.c, actions/pieAction.c, actions/action.c, actions/appAction.c, actions/keyAction.c, actions/uriAction.c, themes/themeImporter.c, themes/theme.c, themes/sliceLayer.c, themes/centerLayer.c, renderers/sliceRenderer.c, renderers/centerRenderer.c, renderers/pieRenderer.c, renderers/pieWindow.c, gui/piePreviewRenderer.c, gui/iconSelectWindow.c, gui/indicator.c, gui/piePreviewSliceRenderer.c, gui/pieOptionsWindow.c, gui/piePreviewAddSign.c, gui/piePreviewDeleteSign.c, gui/newsWindow.c, gui/sliceTypeList.c, gui/triggerSelectButton.c, gui/preferencesWindow.c, gui/tipViewer.c, gui/themeList.c, gui/piePreview.c, gui/pieList.c, gui/aboutWindow.c, gui/newSliceWindow.c, gui/pieComboList.c, gui/piePreviewCenter.c
error: Package `libbamf3' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
src/CMakeFiles/gnome-pie.dir/build.make:115: recipe for target 'src/daemon.c' failed
make[2]: *** [src/daemon.c] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/CMakeFiles/gnome-pie.dir/all' failed
make[1]: *** [src/CMakeFiles/gnome-pie.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

---

However, i have libbamf3 here:

/usr/lib/x86_64-linux-gnu/libbamf3.so.0
/usr/lib/x86_64-linux-gnu/libbamf3.so.0.0.0

**Comment by Simmesimme** [comment]
The missing file is the vala wrapping for libbamf3 (vapi). Under Ubuntu 14.04 this is installed by the package libbamf3-dev and located in /usr/share/vala/vapi/libbamf3.vapi.

For some reason it seems not to be included in Debian jessie
https://packages.debian.org/jessie/amd64/libbamf3-dev/filelist

I'm not sure why that is the case, as a workaround you could try to download the file from [here] (http://apt-browse.org/browse/ubuntu/trusty/main/i386/libbamf3-dev/0.5.1%2B14.04.20140409-0ubuntu1/file/usr/share/vala/vapi/libbamf3.vapi) and save it into a new "vapi" directory in your Gnome-Pie directory. 

Then add this line to the [`vala_precompile_options` in `src/CMakeLists.txt`](https://github.com/Simmesimme/Gnome-Pie/blob/master/src/CMakeLists.txt#L26):

`--vapidir=${CMAKE_SOURCE_DIR}/vapi/`

If this works, I'll have to consider including this... Thanks for the report!

**Comment by nardev** [comment]
I just placed the lib where it expects it to be. I didn't understand your instructions.

Builded, installed but if i try to run it i get his shit:

---

$ gnome-pie
[MESSAGE] Welcome to Gnome-Pie 0.6.8!
[MESSAGE] Loading Pies from "/home/user/.config/gnome-pie/pies.conf".

(gnome-pie:9564): Gtk-CRITICAL **: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-pie:9564): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(gnome-pie:9564): Gtk-CRITICAL **: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-pie:9564): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(gnome-pie:9564): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed


---


Even if i tried to remove my previous configuration, i get this:

---

gnome-pie
[WARNING] Failed to find pie configuration file "pies.conf"! (This should only happen when Gnome-Pie is started for the first time...)
[MESSAGE] Welcome to Gnome-Pie 0.6.8!
[MESSAGE] Creating new configuration file in "/home/user/.config/gnome-pie/pies.conf".
[MESSAGE] Saving Pies to "/home/user/.config/gnome-pie/pies.conf".

(gnome-pie:9712): Gtk-CRITICAL **: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-pie:9712): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(gnome-pie:9712): Gtk-CRITICAL **: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-pie:9712): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed

(gnome-pie:9712): Gtk-CRITICAL **: gtk_container_remove: assertion 'GTK_IS_CONTAINER (container)' failed
Segmentation fault

---

**Comment by Simmesimme** [comment]
This might happen if you have an older version of Gnome-Pie installed globally and are now trying to run Gnome-Pie locally. 

If that is the case, please remove the old version before running the new version. (There should be no `/usr/local/share/gnome-pie` and no `/usr/share/gnome-pie` if you run Gnome-Pie locally). Or install the new version globally. For now it is not possible to have multiple versions of Gnome-Pie in parallel...

Please let me know if that helps, if not we have to investigate further :)

**Comment by nardev** [comment]
yea, you were right.. thnx a lot..

**Comment by nardev** [comment]
again, issue with Debian, that worked few days ago, but now, same configuration, i fixed as you suggested previously for Debian, and it fails this way:

---

./make.sh 
bg/ 101 translated messages, 55 untranslated messages.
de/ 156 translated messages.
es/ 153 translated messages, 3 untranslated messages.
fr/ 153 translated messages, 3 untranslated messages.
it/ 47 translated messages, 19 fuzzy translations, 90 untranslated messages.
ko/ 99 translated messages, 1 fuzzy translation, 56 untranslated messages.
lt/ 153 translated messages, 3 untranslated messages.
pt_BR/ 101 translated messages, 55 untranslated messages.
ru/ 79 translated messages, 21 fuzzy translations, 56 untranslated messages.
zh_CN/ 101 translated messages, 55 untranslated messages.
CMake Error at CMakeLists.txt:20 (vala_precompile):
  Unknown CMake command "vala_precompile".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.0)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/user/Desktop/software-reinstall-oct.2015/Gnome-Pie/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.



And this is what i get there:


---

]
  ignore line: [Thread model: posix]
  ignore line: [gcc version 4.9.2 (Debian 4.9.2-10) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../:/lib/:/usr/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTryCompileExec1781976273' '-rdynamic' '-shared-libgcc' '-mtune=generic' '-march=x86-64']
  link line: [ /usr/lib/gcc/x86_64-linux-gnu/4.9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/4.9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper -plugin-opt=-fresolution=/tmp/cc7YH5cZ.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTryCompileExec1781976273 /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.9/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/4.9 -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../.. CMakeFiles/cmTryCompileExec1781976273.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.9/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crtn.o]
    arg [/usr/lib/gcc/x86_64-linux-gnu/4.9/collect2] ==> ignore
    arg [-plugin] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/4.9/liblto_plugin.so] ==> ignore
    arg [-plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper] ==> ignore
    arg [-plugin-opt=-fresolution=/tmp/cc7YH5cZ.res] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [--sysroot=/] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-o] ==> ignore
    arg [cmTryCompileExec1781976273] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crti.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/4.9/crtbegin.o] ==> ignore
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/4.9] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/4.9]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib]
    arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
    arg [-L/lib/../lib] ==> dir [/lib/../lib]
    arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
    arg [-L/usr/lib/../lib] ==> dir [/usr/lib/../lib]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../..] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../..]
    arg [CMakeFiles/cmTryCompileExec1781976273.dir/CMakeCXXCompilerABI.cpp.o] ==> ignore
    arg [-lstdc++] ==> lib [stdc++]
    arg [-lm] ==> lib [m]
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [-lgcc] ==> lib [gcc]
    arg [-lc] ==> lib [c]
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [-lgcc] ==> lib [gcc]
    arg [/usr/lib/gcc/x86_64-linux-gnu/4.9/crtend.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crtn.o] ==> ignore
  remove lib [gcc_s]
  remove lib [gcc]
  remove lib [gcc_s]
  remove lib [gcc]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.9] ==> [/usr/lib/gcc/x86_64-linux-gnu/4.9]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/4.9/../../..] ==> [/usr/lib]
  implicit libs: [stdc++;m;c]
  implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/4.9;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []



---


Any idea?

**Comment by Simmesimme** [comment]
Sorry for the late delay... in case you're still struggling to get it working: Have you tried to delete the build directory? I've no really idea what's going on but it seems something got messed up there :)

**Comment by nardev** [comment]
of course :+1: 

but at the end i reinstalled whole system, got the new source, build it again and it's ok now.

only issue is that some libs were missing so i had to figure out for 3-4 libs to add them before the build was successful.


it's ok now, working great... like it so much
