### ISSUE TITLE
Pie doesn't appears under the mouse anymore... but is always centered

### ISSUE THREAD

**Issue by rrigaud** [Simmesimme/Gnome-Pie#130]
Hi, sorry for my english, I'm french.
First, thanks a lot for your work because I just love Gnome-pie, it's unique and so fast, so great to use on my daily routine ! It's one of the reasons that I just could not be happy with Windows or OS X...

I work with Archlinux and since the last update (0.6.8-1), when I click on my Mouse Button (Logitech MX500), the pie doesn't appear under my mouse anymore. It is always centered but I didn't check this option in my preferences... ?

Seems like a little bug ?

**Comment by RaphaelRochet** [comment]
Does the pie still appear centered when triggered from command line ?
I'm on Archlinux too but does not see this issue.

**Comment by rrigaud** [comment]
What do you mean by "triggered from the command line" ?
- When triggered from a mouse button : Center
- When triggered from keyboard (Super+A for example) : Center

... even if "Center" is not checked in Preferences...

Is there a way to launch a pie from the command line ? How can I test it ?

**Comment by RaphaelRochet** [comment]
You can open a given pie from a terminal by running :
```gnome-pie -o $id```
Replace ``$id`` by the pie number. You can find the pied number of a pie by looking under the pie icon in pie properties.

**Comment by rrigaud** [comment]
Ok, well... it works, I mean the pie opens at center, not under my mouse, wherever it is located, or whatever I check in my options.

No error message in console.

I don't know...

**Comment by RaphaelRochet** [comment]
The centered flag is stored with the hotkey. You could try to clear the hotkey (using backspace), be sure to uncheck "open in center" for that pie (in the list , and close the settings dialog. Then open the pie from a terminal.

If that fails too, you can try to backup and remove your settings file (~/.config/gnome-pie/pies.conf ) to try with a new one.

**Comment by rrigaud** [comment]
After a little "yaourt -Syu" and a reboot, the problem disappeared !
I don't think this is the update because I update every 2/3 days and I didn't see "gnome-pie" today.

It's wired because I already tryed de reboot a few days ago, and the problem was still there.

Maybe an other package ? Mouse driver or anything else ?

Thanks for your help. Problem solved.
