### ISSUE TITLE
Add .desktop file as new slice

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [Simmesimme/Gnome-Pie#134]
When adding a new slice to a pie, it would be nice to have a slice type that allowed the user to select a .desktop file from his apps.

Maybe scan `/usr/share/applications/` or `~/.local/share/applications/` for the files.

**Comment by Simmesimme** [comment]
That's a pretty good idea! 

But for now, you can also drag those files (like nearly everything you can think of) to the pie preview.

But I like the idea. Let's see if I find some time. I'll post a comment here, when I start working on this feature. If anyone wants to implement this -- just drop a note here!

**Comment by Simmesimme** [comment]
Has been added in v0.7.0. Read the announcement here: http://simmesimme.github.io/news/2016/09/20/gnome-pie-070

Thank you!
