### ISSUE TITLE
Long press of activation and Turbo mode have no effect

### ISSUE THREAD

**Issue by sudoyang** [Simmesimme/Gnome-Pie#136]
I am running gnome-pie on a ubuntu 16.04 thinkpad machine. I use mouse middle key to activate application launcher and use long press of mouse right key to activate 'ALT + TAB' function. But it seems like long press function and turbo mode does not function even I select the there to in the configuration menu. Pretty strange!

**Comment by Simmesimme** [comment]
Hi there !
This has already been fixed in develop (see issue #132). As soon as #134 is resolved, a new version will be released. I will leave this issue open to make other users discover it more easily.
Thanks for the report!

**Comment by sudoyang** [comment]
Thanks for the information!

**Comment by Simmesimme** [comment]
Should be fixed in 0.7.0 :)
