### ISSUE TITLE
Some applications' icons are missing in the function of "Group: Window List"

### ISSUE THREAD

**Issue by sudoyang** [Simmesimme/Gnome-Pie#137]
I am running ubuntu 16.04 with the newest version of gnome-pie. When I use Group:Windows List feature, I have some applications missing their icons, such as okular and image viewer.

Thanks!

**Comment by Simmesimme** [comment]
Hi there! Did this issue arise with the latest version or has this been a problem before?

**Comment by sudoyang** [comment]
It affects current version and also last version.

**Comment by Simmesimme** [comment]
This will be hard to fix. Gnome-Pie is using [Wnck](https://developer.gnome.org/libwnck/stable/) to guess window icon names. It seems that for some applications this does not work. It may be possible to use some heuristics to extract an icon name from the window title (often the application name is part of the window's title and often the icon name is the same as the application name) but this will result in wrong icons quite often I fear.

The best would be to use another library to track the icon names of opened applications. However, I am not aware of any library which does this in an window-manager-independent way. Gnome-Pie used [Bamf](https://unity.ubuntu.com/getinvolved/development/common-libraries/#bamf) before, but this is not available on many systems. And I did not find any application where Bamf gave an icon which was not discovered by Wnck.

So I wonder: Is there a reliable, window-manager-independent way to get icon names for running applications?

**Comment by sudoyang** [comment]
I see. I do not really know the way. Maybe this is the limit of Linux system. Anyway, thanks for the response!

**Comment by sudoyang** [comment]
Btw, is it possible let user manually assign some icon files to those missing ones and the program can remember this configuration?

**Comment by Simmesimme** [comment]
I fear not. The only information I can get (as far as I know) is the window's title. And this changes frequently - Firefox displays the name of the current tab, a music player shows the current track and so on...

**Comment by sudoyang** [comment]
I see. Headache problem.

**Comment by Simmesimme** [comment]
Maybe this has been fixed by 9f8ff5e. f not, please reopen this issue!
