### ISSUE TITLE
An empty indicator icon is shown in Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by gabdub** [Simmesimme/Gnome-Pie#139]
Hi Simon,

No indicator icon is shown in Ubuntu Mate 16.04 unless I added:
gnome_shell = true; 
to line 78 of indicator.vala.
The indicator menu work fine, though.

I don't know how to detect the mate desktop.
screen.get_window_manager_name() returns "Compiz" in my setup.
Any idea?

Best wishes,
Gabriel

**Comment by gabdub** [comment]
The issue is still present in version 0.7.1.

I have to replace:

`this.indicator = new AppIndicator.Indicator.with_path("Gnome-Pie", icon, AppIndicator.IndicatorCategory.APPLICATION_STATUS, path);
`

with:

`this.indicator = new AppIndicator.Indicator("Gnome-Pie", path + "/" + icon + ".svg", AppIndicator.IndicatorCategory.APPLICATION_STATUS);
`

to see the icon.

**Comment by Simmesimme** [comment]
This indicator stuff is really a mess. I will look into it.

**Comment by gabdub** [comment]
It's working in Ubuntu Mate 18.04 (they moved to GTK3).
