### ISSUE TITLE
Gnome-pie closed at pie icon changed

### ISSUE THREAD

**Issue by aliichwan** [Simmesimme/Gnome-Pie#141]
I used Xubuntu 14.04
when I try to change icon on pie, gnome-pie closed
![pemilihan_063](https://cloud.githubusercontent.com/assets/24859180/21797773/9609754c-d743-11e6-837e-702af17f85a9.jpg)

**Comment by Simmesimme** [comment]
Sorry for the late reply. Have you solved the issue? If not, could you please launch Gnome-Pie from a terminal an report any errors?

**Comment by aliichwan** [comment]
After update Gnome-pie in new version the problem solved, thank you

Pada tanggal 12 Mei 2017 2.17 AM, "Simon Schneegans" <
notifications@github.com> menulis:
