### ISSUE TITLE
New Russian translation for gnomepie package

### ISSUE THREAD

**Issue by ashed** [Simmesimme/Gnome-Pie#145]
# Russian translations for gnomepie package
# Русские переводы для пакета gnomepie.
# Copyright (C) 2012 Simon Schneegans <code@simonschneegans.de>
# This file is distributed under the same license as the gnomepie package.
# Roskin <pams@imail.ru>, 2012.
# Simon <code@simonschneegans.de>, 2015. #zanata
msgid ""
msgstr ""
"Project-Id-Version: gnomepie 0.4\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-09-30 18:32+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2017-03-29 09:50+0500\n"
"Last-Translator: ashed <craysy@gmail.com>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: Poedit 1.5.4\n"

#: ../ui/pie_options.ui:53
msgid "Activation Settings"
msgstr "Настройки активации"

#: ../ui/pie_options.ui:153
msgid "Unamed Pie"
msgstr "Безымянный пай"

#: ../ui/pie_options.ui:216
msgid "ID:"
msgstr ""

#: ../ui/pie_options.ui:234
msgid "It's possible to bind mouse buttons as well!"
msgstr "Также возможно назначать кнопки мыши!"

#: ../ui/pie_options.ui:274
msgid "Turbo mode"
msgstr "Турбо-режим"

#: ../ui/pie_options.ui:280 ../ui/pie_options.ui:281
msgid "If checked, the Pie will close when you release the chosen hot key."
msgstr ""
"Если выбрана эта возможность, пай закроется после того, как вы отпустите  "
"клавиши быстрого доступа"

#: ../ui/pie_options.ui:293
msgid "Long press for activation"
msgstr "Продолжительное нажатие для активации"

#: ../ui/pie_options.ui:299 ../ui/pie_options.ui:300
msgid ""
"If checked, the Pie will only open if you press this hot key a bit longer."
msgstr ""
"Если выбрана эта возможность, пай откроется только, если вы продолжительно "
"зажмёте эту клавишу быстрого доступа."

#: ../ui/pie_options.ui:312
msgid "Open Pie centered on the screen"
msgstr "Открыть пай по центру экрана"

#: ../ui/pie_options.ui:318 ../ui/pie_options.ui:319
msgid ""
"If checked, the Pie will open in the middle of your screen. Else it will pop "
"up at your pointer."
msgstr ""
"Если выбрана эта возможность, пай откроется в центре вашего экрана. А также "
"может открываться чуть выше вашего курсора."

#: ../ui/pie_options.ui:331
msgid "Warp mouse pointer to center of Pie"
msgstr "Деформировать указатель мыши к центру Пая"

#: ../ui/pie_options.ui:337 ../ui/pie_options.ui:338
msgid ""
"If checked, the mouse pointer will be warped to the center of the Pie. This "
"allows for quick selections even if the Pie is opened at the screen's "
"boundary."
msgstr "Если отмечено"

#: ../ui/pie_options.ui:356
msgid "Activation options"
msgstr "Параметры активации"

#: ../ui/pie_options.ui:547
msgid "Automatically select the best pie shape"
msgstr "Автоматически выбирать лучшую форму пая"

#: ../ui/pie_options.ui:551
msgid ""
"If checked, the shape will be automatically selected to minimize mouse "
"travelling."
msgstr ""
"Если отмечено, форма будет автоматически выбрана для минимизации перемещения "
"мыши."

#: ../ui/pie_options.ui:571
msgid "Pie shape"
msgstr "Форма пая"

#: ../ui/slice_select.ui:8
msgid "Slice Options"
msgstr "Параметры Фрагмента"

#: ../ui/slice_select.ui:140
msgid "There are no options for this Slice type."
msgstr "Отсутствуют параметры для этого типа фрагмента"

#: ../ui/slice_select.ui:166
msgid "Name of the Slice "
msgstr "Название фрагмента"

#: ../ui/slice_select.ui:204
msgid "URI to open"
msgstr "URI для открытия"

#: ../ui/slice_select.ui:242
msgid "Command to execute"
msgstr "Команда для выполнения"

#: ../ui/slice_select.ui:280
msgid "Hotkey to press"
msgstr "Клавиша быстрого доступа для нажатия"

#: ../ui/slice_select.ui:309
msgid "Pie to open"
msgstr "Пай для открытия"

#: ../ui/slice_select.ui:338
msgid "Is Quick Action"
msgstr "Это быстрое действие"

#: ../ui/slice_select.ui:353 ../ui/slice_select.ui:354
msgid "This Slice will be executed when you click in the middle of the Pie."
msgstr "Эта фрагмент будет выполнен, после нажатия в центре пая"

#: ../ui/slice_select.ui:386
msgid "Slice options"
msgstr "Параметры фрагмента"

#: ../ui/icon_select.ui:9
msgid "Select an icon"
msgstr "Выберите значок"

#: ../ui/icon_select.ui:103
msgid "Icon Theme"
msgstr "Тема значков"

#: ../ui/icon_select.ui:123
msgid "Custom Icon"
msgstr "Настроить значок"

#: ../ui/preferences.ui:7 ../../src/gui/preferencesWindow.vala:78
msgid "Gnome-Pie Settings"
msgstr "Настройки Gnome-Pie"

#: ../ui/preferences.ui:41
msgid "Start Gnome-Pie on login"
msgstr "Запускать Gnome-Pie при загрузке системы"

#: ../ui/preferences.ui:47 ../ui/preferences.ui:48
msgid "If checked, Gnome-Pie will start silently everytime you log in."
msgstr ""
"Если выбрана эта возможность, Gnome-Pie будет фоново запускаться после входа "
"в систему."

#: ../ui/preferences.ui:60
msgid "Display panel icon "
msgstr "Показывать значок на панели "

#: ../ui/preferences.ui:66 ../ui/preferences.ui:67
msgid ""
"If not checked, you can access this menu by launching Gnome-Pie a second "
"time."
msgstr ""
"Если эта возможность не выбрана, вы можете получить доступ к этому меню "
"запустив Gnome-Pie второй раз."

#: ../ui/preferences.ui:79
msgid "Select Slices by typing their names"
msgstr "Выберите фрагменты, введя их имена"

#: ../ui/preferences.ui:85 ../ui/preferences.ui:86
msgid ""
"If checked, you can select items in a Pie by typing their names. Otherwise "
"you can activate them with a hotkey (which can be displayed by pressing ALT "
"when a Pie is openened)."
msgstr ""
"Если отмечено, вы можете выбрать элементы в Пае, введя их имена. Иначе вы "
"можете активировать их горячей клавишей (которая может отображаться при "
"нажатии клавиши ALT при открытии Пая)."

#: ../ui/preferences.ui:98
msgid "Display Slice labels"
msgstr "Показывать значок на панели "

#: ../ui/preferences.ui:104 ../ui/preferences.ui:105
msgid ""
"Displays the name of each Slice next to it. Only available if supported by "
"the theme."
msgstr ""
"Отображать имя каждого фрагмента рядом с ним. Доступно только если "
"поддерживается темой."

#: ../ui/preferences.ui:139
msgid "Activation radius"
msgstr "Радиус активации"

#: ../ui/preferences.ui:179
msgid "Global scale"
msgstr "Общий масштаб"

#: ../ui/preferences.ui:219
msgid "Maximum slices per pie"
msgstr "Максимум фрагментов на Пай"

#: ../ui/preferences.ui:302
msgid "Import a theme from a file."
msgstr "Импорт темы из файла."

#: ../ui/preferences.ui:323
msgid "Delete the selected theme."
msgstr "Удалить выделенную тему."

#: ../ui/preferences.ui:344
msgid "Export the selected theme for sharing."
msgstr "Поделиться выделенной темой."

#: ../ui/preferences.ui:392
msgid "Open a tutorial on how to create new themes for Gnome-Pie."
msgstr "Открыть учебник о создании новых тем для Gnome-Pie."

#: ../ui/preferences.ui:442 ../../src/gui/preferencesWindow.vala:109
msgid "General Settings"
msgstr "Основные настройки"

#: ../ui/preferences.ui:634
msgid ""
"<b><big>This Pie is empty!</big>\n"
"\n"
"Start adding Slices to it!</b> This can be done by dragging stuff to the "
"plus sign below. You can try a lot! For example application launchers or "
"folders. Even URLs from your browser are possible...\n"
"\n"
"For manual and advanced configuration click on the plus sign."
msgstr ""
"<b><big>Этот Пай пуст!</big>\n"
"\n"
"Начните добавлять фрагменты!</b> Это можно сделать, перетащив что-либо на "
"знак плюса ниже. Вы можете попробовать много всякого! Например, ярлыки "
"запуска приложений или папки приложений. Даже URL-адреса из вашего "
"браузера...\n"
"\n"
"Для ручной и расширенной конфигурации нажмите на знак плюса."

#: ../ui/preferences.ui:655
msgid ""
"<b><big>You have no Pies!</big>\n"
"\n"
"Start by creating one! </b> This can be done by clicking on the tiny little "
"plus sign in the lower left corner."
msgstr ""
"<b><big>Отсутствуют паи!</big>\n"
"\n"
"Начните с создания пая! </b> Выполните это щёлкнув на небольшом значке "
"плюсав нижнем левом углу."

#: ../ui/preferences.ui:741 ../../src/gui/preferencesWindow.vala:110
msgid "Pie Settings"
msgstr "Настройки Пая"

#: ../../src/actions/keyAction.vala:34
msgid "Press hotkey"
msgstr "Нажмите сочетание клавиш быстрого доступа"

#: ../../src/actions/keyAction.vala:36
msgid "Simulates the activation of a hotkey."
msgstr "Имитирует активацию сочетания клавиш быстрого доступа."

#: ../../src/actions/uriAction.vala:34
msgid "Open URI"
msgstr "Открыть URI"

#: ../../src/actions/uriAction.vala:36
msgid "Opens a given location. You may use URL's or files paths."
msgstr "Открыть заданный адрес. Можно использовать URL или пути к файлам."

#: ../../src/actions/actionRegistry.vala:119
msgid "Trash"
msgstr "Корзина"

#: ../../src/actions/appAction.vala:34
msgid "Launch application"
msgstr "Запустить приложение"

#: ../../src/actions/appAction.vala:36
msgid "Executes the given command."
msgstr "Выполнить заданную команду."

#: ../../src/actions/pieAction.vala:34
msgid "Open Pie"
msgstr "Открыть пай"

#: ../../src/actions/pieAction.vala:36
msgid "Opens another Pie of Gnome-Pie. You may create sub menus this way."
msgstr "Открыть ещё один пай Gnome-Pie. Таким образом можно создать подменю."

#: ../../src/gui/preferencesWindow.vala:79
msgid "bake your pies!"
msgstr "выпекайте паи!"

#: ../../src/gui/preferencesWindow.vala:235
msgid "Pies can be opened with the terminal command \"gnome-pie --open=ID\"."
msgstr "Паи можно открыть с помощью команды терминала \"gnome-pie --open=ID\"."

#: ../../src/gui/preferencesWindow.vala:236
msgid "Feel free to visit Gnome-Pie's homepage at %s!"
msgstr "Посетите страницу Gnome-Pie %s!"

#: ../../src/gui/preferencesWindow.vala:237
msgid "If you want to give some feedback, please write an e-mail to %s!"
msgstr "Если вы хотите дать обратную связь, напишите письмо по адресу %s!"

#: ../../src/gui/preferencesWindow.vala:238
msgid "You can support the development of Gnome-Pie by donating via %s."
msgstr "Вы можете поддержать развитие Gnome-Pie, пожертвовав через %s."

#: ../../src/gui/preferencesWindow.vala:239
msgid ""
"Translating Gnome-Pie to your language is easy. Translations are managed at "
"%s."
msgstr "Перевод Gnome-Пая на ваш язык легок. Переводы управляются на %s."

#: ../../src/gui/preferencesWindow.vala:240
msgid ""
"It's easy to create new themes for Gnome-Pie. Read the <a "
"href='%s'>Tutorial</a> online."
msgstr ""
"Легко создавать новые темы для Gnome-Pie. Прочтите <a href='%s'>Учебник</a> "
"онлайн."

#: ../../src/gui/preferencesWindow.vala:241
msgid "It's usually a good practice to have at most twelve slices per pie."
msgstr ""
"Обычно хорошая практика состоит в том, чтобы иметь не более двенадцати "
"фрагментов на Пай."

#: ../../src/gui/preferencesWindow.vala:242
msgid "You can export themes you created and share them with the community!"
msgstr "Вы можете экспортировать созданные темы и делиться ими с сообществом!"

#: ../../src/gui/preferencesWindow.vala:243
msgid "The source code of Gnome-Pie is available on %s."
msgstr "Исходный код Gnome-Pie доступен на %s."

#: ../../src/gui/preferencesWindow.vala:244
msgid "Bugs can be reported at %s!"
msgstr "Об ошибках можно сообщить по адресу %s!"

#: ../../src/gui/preferencesWindow.vala:245
msgid "Suggestions can be posted on %s!"
msgstr "Предложения можно размещать на %s!"

#: ../../src/gui/preferencesWindow.vala:246
msgid ""
"An awesome companion of Gnome-Pie is %s. It will make using your computer "
"feel like magic!"
msgstr ""
"Удивительный спутник Gnome-Pie - это %s. Сделайте использование вашего "
"компьютера волшебным!"

#: ../../src/gui/preferencesWindow.vala:247
msgid "You can drag'n'drop applications from your main menu to the pie above."
msgstr ""
"Вы можете перетащить приложения из своего главного меню в указанный выше Пай."

#: ../../src/gui/preferencesWindow.vala:248
msgid ""
"You may drag'n'drop URLs and bookmarks from your internet browser to the pie "
"above."
msgstr ""
"Вы можете перетащить URL-адреса и закладки из своего интернет-браузера в "
"указанный выше Пай."

#: ../../src/gui/preferencesWindow.vala:249
msgid ""
"You can drag'n'drop files and folders from your file browser to the pie "
"above."
msgstr ""
"Вы можете перетащить файлы и папки из браузера файлов в указанный выше Пай."

#: ../../src/gui/preferencesWindow.vala:250
msgid ""
"You can drag'n'drop pies from the list on the left into other pies in order "
"to create sub-pies."
msgstr ""
"Вы можете перетаскивать Паи из списка слева в другие Паи, чтобы создать "
"субПаи."

#: ../../src/gui/preferencesWindow.vala:251
msgid ""
"You can drag'n'drop pies from the list on the left to your desktop or dock "
"to create a launcher for this pie."
msgstr ""
"Вы можете перетаскивать Паи из списка слева на свой рабочий стол или док, "
"чтобы создать ярлык запуска для этого Пая."

#: ../../src/gui/preferencesWindow.vala:401
msgid "Sucessfully imported new theme!"
msgstr "Успешно импортирована новая тема!"

#: ../../src/gui/preferencesWindow.vala:415
msgid "An error occured while importing the theme: Failed to extract theme!"
msgstr "При импорте темы произошла ошибка: Не удалось извлечь тему!"

#: ../../src/gui/preferencesWindow.vala:419
msgid ""
"An error occured while importing the theme: A theme with this name does "
"already exist!"
msgstr "При импорте темы произошла ошибка: тема с этим именем уже существует!"

#: ../../src/gui/preferencesWindow.vala:423
msgid ""
"An error occured while importing the theme: Theme archive does not contain a "
"valid theme!"
msgstr ""
"При импорте темы произошла ошибка: в архиве темы нет действительной темы!"

#: ../../src/gui/preferencesWindow.vala:427
msgid ""
"An error occured while importing the theme: Failed to open theme archive!"
msgstr "При импорте темы произошла ошибка: Не удалось открыть тему!"

#: ../../src/gui/preferencesWindow.vala:451
msgid "Do you really want to delete the selected theme from %s?"
msgstr "Вы действительно хотите удалить выбранную тему из %s?"

#: ../../src/gui/preferencesWindow.vala:528
msgid "New Pie"
msgstr "Новый пай"

#: ../../src/gui/preferencesWindow.vala:543
msgid ""
"Do you really want to delete the selected Pie with all contained Slices?"
msgstr ""
"Вы действительно хотите удалить выделенный пай, со всеми содержащимися в нём "
"фрагментами?"

#: ../../src/gui/piePreview.vala:148
msgid "Do you really want to delete this Slice?"
msgstr "Вы действительно хотите удалить этот фрагмент?"

#: ../../src/gui/sliceTypeList.vala:60
msgid "Slice types"
msgstr "Типы фрагментов"

#: ../../src/gui/piePreviewRenderer.vala:419
msgid "Click to edit"
msgstr "Щелчок для правки"

#: ../../src/gui/piePreviewRenderer.vala:419
#: ../../src/gui/piePreviewRenderer.vala:434
msgid "Drag to move"
msgstr "Перемещайте таская"

#: ../../src/gui/piePreviewRenderer.vala:422
msgid "Click to add a new Slice"
msgstr "Щелчок - доб-ть нов. фрагмент"

#: ../../src/gui/piePreviewRenderer.vala:426
msgid "Drop to add as new Slice"
msgstr "Перетащить - добавить как новый фрагмент"

#: ../../src/gui/piePreviewRenderer.vala:429
msgid "Drop to move Slice"
msgstr "Перетащить - переместить фрагмент"

#: ../../src/gui/piePreviewRenderer.vala:434
msgid "Click to delete"
msgstr "Щелчок - удалить"

#: ../../src/gui/pieList.vala:77
msgid "Pies"
msgstr "Паи"

#: ../../src/gui/iconSelectWindow.vala:182
msgid "All icons"
msgstr "Все значки"

#: ../../src/gui/iconSelectWindow.vala:183
#: ../../src/pies/defaultConfig.vala:36
msgid "Applications"
msgstr "Приложения"

#: ../../src/gui/iconSelectWindow.vala:184
msgid "Actions"
msgstr "Действия"

#: ../../src/gui/iconSelectWindow.vala:185
msgid "Places"
msgstr "Переходы"

#: ../../src/gui/iconSelectWindow.vala:186
msgid "File types"
msgstr "Типы файлов"

#: ../../src/gui/iconSelectWindow.vala:187
msgid "Emotes"
msgstr "Эмоции"

#: ../../src/gui/iconSelectWindow.vala:188
msgid "Miscellaneous"
msgstr "Прочее"

#: ../../src/gui/iconSelectWindow.vala:261
msgid "All supported image formats"
msgstr "Все поддерживаемые форматы изображений"

#: ../../src/gui/newSliceWindow.vala:292
msgid "Rename me!"
msgstr "Переименуйте меня!"

#: ../../src/gui/pieOptionsWindow.vala:274
msgid ""
"This hotkey is already assigned to the pie \"%s\"! \n"
"\n"
"Please select another one or cancel your selection."
msgstr ""
"Эта клавиша быстрого доступа уже назначена паю \"%s\"! \n"
"\n"
"Пожалуйста, выберите другую или отмените выбор."

#: ../../src/gui/themeList.vala:59
msgid "Themes"
msgstr "Темы"

#: ../../src/gui/themeList.vala:108
msgid "by"
msgstr "от"

#: ../../src/gui/indicator.vala:126
msgid "_Preferences"
msgstr "Настройки"

#: ../../src/gui/indicator.vala:135
msgid "_About"
msgstr "О программе"

#: ../../src/gui/indicator.vala:150
msgid "_Quit"
msgstr "Выход"

#: ../../src/gui/newsWindow.vala:64
msgid "_Close"
msgstr "Закрыть"

#: ../../src/gui/triggerSelectButton.vala:64
msgid "Press a hotkey ..."
msgstr "Нажмите горячие клавиши"

#: ../../src/utilities/key.vala:65 ../../src/utilities/bindingManager.vala:186
#: ../../src/utilities/trigger.vala:195 ../../src/utilities/trigger.vala:280
#: ../../src/utilities/trigger.vala:281
msgid "Not bound"
msgstr "Нет привязки"

#: ../../src/utilities/trigger.vala:182
msgid "Button %i"
msgstr "Кнопка %i"

#: ../../src/utilities/trigger.vala:185
msgid "LeftButton"
msgstr "ЛеваяКнопка"

#: ../../src/utilities/trigger.vala:187
msgid "RightButton"
msgstr "ПраваяКнопка"

#: ../../src/utilities/trigger.vala:189
msgid "MiddleButton"
msgstr "СредняяКнопка"

#: ../../src/utilities/trigger.vala:216
msgid "Turbo"
msgstr "Турбо"

#: ../../src/utilities/trigger.vala:220 ../../src/utilities/trigger.vala:222
msgid "Delayed"
msgstr "Задержка"

#: ../../src/utilities/trigger.vala:226 ../../src/utilities/trigger.vala:228
msgid "Centered"
msgstr "По центру"

#: ../../src/utilities/trigger.vala:232 ../../src/utilities/trigger.vala:234
msgid "Warp"
msgstr "Деформация"

#: ../../src/utilities/trigger.vala:238 ../../src/utilities/trigger.vala:240
msgid "Auto-shaped"
msgstr "Автоформа"

#: ../../src/utilities/trigger.vala:243 ../../src/utilities/trigger.vala:245
msgid "Quarter pie"
msgstr "Четверть Пая"

#: ../../src/utilities/trigger.vala:249 ../../src/utilities/trigger.vala:251
msgid "Half pie"
msgstr "Половина Пая"

#: ../../src/themes/theme.vala:169
msgid "Successfully exported the theme \"%s\"!"
msgstr "Тема экспортирована успешно \"%s\"!"

#: ../../src/themes/theme.vala:176
msgid ""
"An error occured while exporting the theme \"%s\"! Please check the console "
"output."
msgstr "При экспорте темы произошла ошибка \"%s\"! Проверьте вывод консоли."

#: ../../src/actionGroups/windowListGroup.vala:34
msgid "Group: Window List"
msgstr "Группа: Список окон"

#: ../../src/actionGroups/windowListGroup.vala:36
msgid "Shows a Slice for each of your opened Windows. Almost like Alt-Tab."
msgstr ""
"Показать фрагмент для каждого из открытых окон. Как это делает Alt-Tab."

#: ../../src/actionGroups/clipboardGroup.vala:64
msgid "Group: Clipboard"
msgstr "Группа: Буфер обмена"

#: ../../src/actionGroups/clipboardGroup.vala:66
msgid "Manages your Clipboard."
msgstr "Управляет вашим буфером обмена."

#: ../../src/actionGroups/devicesGroup.vala:35
msgid "Group: Devices"
msgstr "Группа: Устройства"

#: ../../src/actionGroups/devicesGroup.vala:37
msgid "Shows a Slice for each plugged in devices, like USB-Sticks."
msgstr "Показать фрагмент для подключённых устройств, например USB-накопителя."

#: ../../src/actionGroups/devicesGroup.vala:85
msgid "Root"
msgstr "Файловая система"

#: ../../src/actionGroups/menuGroup.vala:35
msgid "Group: Main menu"
msgstr "Группа: Основное меню"

#: ../../src/actionGroups/menuGroup.vala:37
msgid "Displays your main menu structure."
msgstr "Отображает структуру вашего основного меню."

#: ../../src/actionGroups/workspaceWindowListGroup.vala:35
msgid "Group: Window List for current workspace"
msgstr "Группа: Список окон для текущего рабочего пространства"

#: ../../src/actionGroups/workspaceWindowListGroup.vala:37
msgid "Shows a Slice for each of your opened windows on the current workspace."
msgstr ""
"Показать фрагмент для каждого из открытых окон в текущем рабочем "
"пространстве."

#: ../../src/actionGroups/sessionGroup.vala:35
msgid "Group: Session Control"
msgstr "Группа: Управление сеансом"

#: ../../src/actionGroups/sessionGroup.vala:37
msgid "Shows a Slice for Shutdown, Reboot, and Hibernate."
msgstr ""
"Показывает фрагмент для операций выключения, перезагрузки и спящего режима."

#: ../../src/actionGroups/sessionGroup.vala:60
msgid "Shutdown"
msgstr "Выключить"

#: ../../src/actionGroups/sessionGroup.vala:63
msgid "Logout"
msgstr "Завершить сеанс"

#: ../../src/actionGroups/sessionGroup.vala:66
msgid "Reboot"
msgstr "Перезагрузить"

#: ../../src/actionGroups/bookmarkGroup.vala:36
msgid "Group: Bookmarks"
msgstr "Группа: Закладки"

#: ../../src/actionGroups/bookmarkGroup.vala:38
msgid "Shows a Slice for each of your directory Bookmarks."
msgstr "Показать фрагмент, содержащий закладки папок."

#: ../../src/pies/defaultConfig.vala:29
msgid "Multimedia"
msgstr "Мультимедиа"

#: ../../src/pies/defaultConfig.vala:30
msgid "Next Track"
msgstr "Следующая композиция"

#: ../../src/pies/defaultConfig.vala:31
msgid "Stop"
msgstr "Остановить"

#: ../../src/pies/defaultConfig.vala:32
msgid "Previous Track"
msgstr "Предыдущая композиция"

#: ../../src/pies/defaultConfig.vala:33
msgid "Play/Pause"
msgstr "Воспроизвести или приостановить"

#: ../../src/pies/defaultConfig.vala:45
msgid "Bookmarks"
msgstr "Закладки"

#: ../../src/pies/defaultConfig.vala:50
msgid "Session"
msgstr "Сеанс"

#: ../../src/pies/defaultConfig.vala:54
msgid "Main Menu"
msgstr "Основное меню"

#: ../../src/pies/defaultConfig.vala:58
msgid "Window"
msgstr "Окно"

#: ../../src/pies/defaultConfig.vala:59
msgid "Scale"
msgstr "Масштаб"

#: ../../src/pies/defaultConfig.vala:60
msgid "Minimize"
msgstr "Свернуть"

#: ../../src/pies/defaultConfig.vala:61
msgid "Close"
msgstr "Закрыть"

#: ../../src/pies/defaultConfig.vala:62
msgid "Maximize"
msgstr "Развернуть"

#: ../../src/pies/defaultConfig.vala:63
msgid "Restore"
msgstr "Восстановить"

**Comment by Simmesimme** [comment]
Thank you! I will include this as soon as possible!

**Comment by Simmesimme** [comment]
Done. Thank you!
