### ISSUE TITLE
Turbo mode not working with touchpad.

### ISSUE THREAD

**Issue by DroWnThePoor** [Simmesimme/Gnome-Pie#146]
I'm using the PPA 0.7.0 version on Elementary OS 0.4 Loki
On an HP Envy x360-m6 convertible which shows a SynPS/2 Synaptics Touchpad
The symptom is with turbo mode enabled, the touchpad no longer moves the mouse,
So when released the widget closes as it should.
This does not happen when using an external USB keyboard.

Is there any fix or conf I could change to correct this?

**Comment by Simmesimme** [comment]
Sorry for the late reply. How do you trigger the Pie? With a key binding? I guess that some drivers may deactivate the touchpad when keys are pressed in order to prevent accidental clicks. Can this be the issue?

**Comment by Simmesimme** [comment]
Please re-open if that's still an issue!
