### ISSUE TITLE
In "Group: Window List", some windows do not appear

### ISSUE THREAD

**Issue by tcorreabr** [Simmesimme/Gnome-Pie#149]
Gnome Extensions windows, for example.

**Comment by Simmesimme** [comment]
Thanks for reporting the issue!

 When I find the time I will have look at this. However I am currently working on a new project (something like Gnome-Pie 2). So it may take some time! 

If someone wants to have a look a this... I am happily accepting pull requests!

Same goes for your other issue (#148)

**Comment by Simmesimme** [comment]
Fixed by 9f8ff5e. Thank you!
