### ISSUE TITLE
can not get gnome-pie menu class and title from xprop

### ISSUE THREAD

**Issue by jerome-diver** [Simmesimme/Gnome-Pie#153]
I would like to use gnome-pie with i3, but for that, i need to have xprop informations for be able to run gnome-pie menu has floating windows.
xprop give information about windows the mouse point... but it can not grab mouse event because gnome-pie need it also.
Then, a solution may be to call gnome-pie menu from terminal...for try something like: 
`gnome-pi_menu; sleep 2; xprop -id $(xdotool getactivewindow)`
 but command `gnome-pie` do call gnome-pie configuration window, and not gnome-pie menu... 
How to call gnome-pie menu from terminal ?

**Comment by Simmesimme** [comment]
It's documented over there: http://simmesimme.github.io/gnome-pie.html#toc7

Just open a pie with `gnome-pie --open 123` and replace `123` with the ID of your pie. The ID can be found in the pie options in the configuration menu. Does this solve your problem?

**Comment by adberard** [comment]
So I tryed 
`gnome-pie -o 615; sleep 2; xprop -id $(xdotool getactivewindow)
`
But xdotool dont see gnome pie menu as active window. Can you give us the name of the class of thoses menu windows ?

**Comment by adberard** [comment]
`
93 | Gdk.set_program_class("gnome-pie-" + id);
-- | --
94 |  
95 | var window = new PieWindow();
96 | window.load_pie(pie);
… |  
115 | Gdk.set_program_class("Gnome-pie");
`
so I found the class name but apparently the position of the window isnt set on the mouse and doesnt float above others windows. anyone succeeded to make it work with i3 ?

**Comment by Simmesimme** [comment]
Please re-open this if it is still an issue!
