### ISSUE TITLE
Full feature version for fedora and other distros

### ISSUE THREAD

**Issue by Majo111** [Simmesimme/Gnome-Pie#155]
Hi,
Version for fedora is poor against ubuntu. Add missed features to the fedora, please.

**Comment by Simmesimme** [comment]
I am not the maintainer of the Fedora version. You should check the version you have installed. In Ubuntu it's 0.7.1 currently. If this is newer, you can still compile Gnome-Pie yourself from source. It's actually pretty easy:

http://simmesimme.github.io/gnome-pie.html#installation-of-gnome-pie
