### ISSUE TITLE
build not possible

### ISSUE THREAD

**Issue by Naik-NLZ** [Simmesimme/Gnome-Pie#156]
whenever I try to build latest version  on Debian testing/unstable i get 
`Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: 
Id flags:  

The output was:
1
/usr/bin/ld: Scrt1.o kann nicht gefunden werden: Datei oder Verzeichnis nicht gefunden
/usr/bin/ld: crti.o kann nicht gefunden werden: Datei oder Verzeichnis nicht gefunden
collect2: error: ld returned 1 exit status

Determining if the C compiler works failed with the following output:
Change Dir: /home/naik/bin/Gnome-Pie/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_3391a/fast"
/usr/bin/make -f CMakeFiles/cmTC_3391a.dir/build.make CMakeFiles/cmTC_3391a.dir/build
make[1]: Verzeichnis „/home/naik/bin/Gnome-Pie/build/CMakeFiles/CMakeTmp“ wird betreten
Building C object CMakeFiles/cmTC_3391a.dir/testCCompiler.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_3391a.dir/testCCompiler.c.o   -c /home/naik/bin/Gnome-Pie/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_3391a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3391a.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_3391a.dir/testCCompiler.c.o  -o cmTC_3391a 
/usr/bin/ld: Scrt1.o kann nicht gefunden werden: Datei oder Verzeichnis nicht gefunden
/usr/bin/ld: crti.o kann nicht gefunden werden: Datei oder Verzeichnis nicht gefunden
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_3391a.dir/build.make:97: die Regel für Ziel „cmTC_3391a“ scheiterte
make[1]: *** [cmTC_3391a] Fehler 1
make[1]: Verzeichnis „/home/naik/bin/Gnome-Pie/build/CMakeFiles/CMakeTmp“ wird verlassen
Makefile:126: die Regel für Ziel „cmTC_3391a/fast“ scheiterte
make: *** [cmTC_3391a/fast] Fehler 2

`

**Comment by Simmesimme** [comment]
Is this still an issue? Are you sure you have set up your build environment correctly? This looks as if CMake fails to identify your C compiler.
