### ISSUE TITLE
Gnome-Pie not working with latest update of gdm and gnome-session in debian testing/buster

### ISSUE THREAD

**Issue by Jeansen** [Simmesimme/Gnome-Pie#157]
If I install any of the packages below (which I have to because they depend on each other), Gnome-Pie will no longer work. On one hand it is not loaded and on startup - at least it does not appear in the panel menu. On the other hand shortcuts to bring it up do not work and I cannot apply new shortcuts in the configuration window (field is grayed out).

![screenshot sun aug 27 2017 10 41 59 gmt 0200 cest 1330x275](https://user-images.githubusercontent.com/9211499/29748307-639615ae-8b14-11e7-942e-9da12ca529d9.png)

**Comment by Simmesimme** [comment]
Sounds like you are using a Wayland session? When the shortcut field is grayed out, there should be a comment underneath explaining the issue. You can read more here: http://simmesimme.github.io/news/2017/07/09/gnome-pie-071

**Comment by Jeansen** [comment]
Yes, that was it. The default since the above update  seems to be wayland because there is now an entry in GDM saying " Gnome on Xorg" instead of "Gnome on Wayland". Using Xorg solves the issue. 

I hope there will be a way to get your great tool ported to wayland. I have not much experience in Vala but if I can help with some development in the future; please let me know. I simply do not believe there will be no way to get this tool running on wayland, too!
