### ISSUE TITLE
Any hotkey with Super needs to be pressed twice.

### ISSUE THREAD

**Issue by different55** [Simmesimme/Gnome-Pie#160]
Running Budgie on Solus 3. The GNOME stuff is all on version 3.26.2, GNOME-Pie is version 0.7.1. Other applications (SimpleScreenRecorder) seem to bind to Super hotkeys just fine.

If I set a pie's hotkey to Super+Space or Super+Tab or Super+Q or really any key, I need to press the other key twice before the pie will appear, and Super needs to stay held down. So essentially the hotkey becomes Super+Q+Q. Adding another modifier like Alt+Super+Q or Ctrl+Super+Q makes this go away.

The double-pressing trick doesn't work for Super+Space. Other modifier keys don't appear to be affected.

EDIT: Might not be a bug in GNOME-Pie, also found this behavior with some Super hotkeys in Alfred.

**Comment by Simmesimme** [comment]
Thanks for the report and sorry for the late reply! I cannot reproduce this issue. Is it still relevant for you?

**Comment by different55** [comment]
Well, I've migrated to Debian Sid w/ GNOME in the mean time and can't reproduce it here. With that in mind I'm thinking it's a bug in Budgie, not Gnome Pie.
