### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by JoergFF** [Simmesimme/Gnome-Pie#165]
Hi,

there are some typos:

Sucessfully vs. Successfully:
src/gui/preferencesWindow.vala:401:        var message = _("Sucessfully imported new theme!");

occured vs. occurred:
src/gui/preferencesWindow.vala:415:                                message = _("An error occured while importing the theme: Failed to extract theme!");
src/gui/preferencesWindow.vala:419:                            message = _("An error occured while importing the theme: A theme with this name does already exist!");
src/gui/preferencesWindow.vala:423:                        message = _("An error occured while importing the theme: Theme archive does not contain a valid theme!");
src/gui/preferencesWindow.vala:427:                    message = _("An error occured while importing the theme: Failed to open theme archive!");
src/themes/theme.vala:176:            var message = _("An error occured while exporting the theme \"%s\"! Please check the console output.").printf(this.name);

CU
Jörg

**Comment by JoergFF** [comment]
The patch:

[0105-spelling_errors.patch.txt](https://github.com/Simmesimme/Gnome-Pie/files/2359649/0105-spelling_errors.patch.txt)

**Comment by i-need-to-tell-you-something** [comment]
This seems to have been addressed in [0.7.2](http://simmesimme.github.io/news/2018/10/30/gnome-pie-072) so the issue can be closed.
