### ISSUE TITLE
Unclear window name for compositor exclusion

### ISSUE THREAD

**Issue by croots** [Simmesimme/Gnome-Pie#167]
Hello!

I'm running gnome-pie under openbox and I think it's the best launcher for my set up; however, I'm unable to figure out how to add it to the exclusions for compton for casting a shadow. Not doing so appears to cause strange visual effects.

Normally, this exclusion would be done by adding the application name to the compositor; however, I'm unable to identify what to use. I've tried "gnome-pie", "pie", and the names of individual pies to no avail.

Do you have any suggestions for exclusions to try?

Thanks in advance.

**Comment by i-need-to-tell-you-something** [comment]
Hey! I recommend Googling (or DuckDuckGo-ing) "how to identify window in openbox". I know KDE has some built-in tools for it, but maybe OpenBox has as well. If not, then maybe there is a window-manager independent X11 solution for getting a window's name. This question doesn't sound like a problem with Gnome-Pie itself. But I get it might be difficult to find a place to ask this, I would recommend askubuntu.com for all beginner friendly Linux questions. Out of all the StackExchange sites I use that one the most.

That said. My KDE thing is telling me the following information:
```
Class: gnome-pie-109 (gnome-pie gnome-pie-109)
Role:
Type: Dock (panel)
Title: Gnome-Pie
Machine: mypchostname
```
Hope that helps!
