### ISSUE TITLE
failure compiling in void linux

### ISSUE THREAD

**Issue by 46dude** [Simmesimme/Gnome-Pie#168]
[pablo@v01d Gnome-Pie]$ ./make.sh 
bg/ 101 mensajes traducidos, 55 mensajes sin traducir.
de/ 156 mensajes traducidos.
es/ 156 mensajes traducidos.
fr/ 153 mensajes traducidos, 3 mensajes sin traducir.
it/ it//LC_MESSAGES/it.po:25: fin de línea dentro de una cadena
it//LC_MESSAGES/it.po:251:62: secuencia de control ilegal
it//LC_MESSAGES/it.po:252:3: secuencia de control ilegal
it//LC_MESSAGES/it.po:543: palabra clave "_Abbandona" desconocida
it//LC_MESSAGES/it.po:543:18: syntax error
it//LC_MESSAGES/it.po:544: fin de línea dentro de una cadena
it//LC_MESSAGES/it.po:606:42: secuencia de control ilegal
it//LC_MESSAGES/it.po:606:45: syntax error
it//LC_MESSAGES/it.po:606: palabra clave "s" desconocida
it//LC_MESSAGES/it.po:612:68: secuencia de control ilegal
it//LC_MESSAGES/it.po:612:71: syntax error
it//LC_MESSAGES/it.po:612: palabra clave "s" desconocida
msgfmt: se encontraron 12 errores fatales
ko/ 99 mensajes traducidos, 1 traducción difusa, 56 mensajes sin traducir.
lt/ 156 mensajes traducidos.
nl_NL/ 153 mensajes traducidos.
pl/ 63 mensajes traducidos, 93 mensajes sin traducir.
pt_BR/ 101 mensajes traducidos, 55 mensajes sin traducir.
ru/ 155 mensajes traducidos, 1 mensaje sin traducir.
zh_CN/ 101 mensajes traducidos, 55 mensajes sin traducir.
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Vala: /usr/bin/valac  
-- checking for a minimum Vala version of 0.22.0
--   found Vala, version 0.44.3
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.1") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.8
-- Checking for module 'appindicator3-0.1'
--   Found appindicator3-0.1, version 12.10.0
-- Checking for module 'libwnck-3.0'
--   Found libwnck-3.0, version 3.30.0
-- Checking for module 'libbamf3'
--   Found libbamf3, version 0.5.4
-- Checking for module 'gio-unix-2.0'
--   Found gio-unix-2.0, version 2.60.2
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Checking for module 'gee-0.8'
--   Found gee-0.8, version 0.20.1
-- Checking for module 'x11'
--   Found x11, version 1.6.7
-- Checking for module 'libxml-2.0'
--   Found libxml-2.0, version 2.9.9
-- Checking for module 'xtst'
--   Found xtst, version 1.2.3
-- Checking for module 'libgnome-menu-3.0'
--   Found libgnome-menu-3.0, version 3.32.0

Summary:
  EXECUTABLE_OUTPUT_PATH = /home/pablo/Git/Gnome-Pie
  VALA_EXECUTABLE = /usr/bin/valac
Libs:
  GTK3_LIBRARIES = gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
  CAIRO_LIBRARIES = cairo
  GEE_LIBRARIES = gee-0.8;gobject-2.0;glib-2.0
  INDICATOR_LIBRARIES = 
  INDICATOR3_LIBRARIES = appindicator3;dbusmenu-glib;gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
  XML_LIBRARIES = xml2
  XTST_LIBRARIES = Xtst
  GMENU_LIBRARIES = 
  GMENU3_LIBRARIES = gnome-menu-3;gio-2.0;gobject-2.0;glib-2.0
  X11_LIBRARIES = X11
  WNCK_LIBRARIES = wnck-3;gtk-3;gdk-3;pangocairo-1.0;pango-1.0;atk-1.0;cairo-gobject;cairo;gdk_pixbuf-2.0;gio-2.0;gobject-2.0;glib-2.0
  ARCHIVE_LIBRARIES = ARCHIVE_LIB-NOTFOUND

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ARCHIVE_LIB
    linked by target "gnome-pie" in directory /home/pablo/Git/Gnome-Pie/src

-- Configuring incomplete, errors occurred!
See also "/home/pablo/Git/Gnome-Pie/build/CMakeFiles/CMakeOutput.log".
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.

**Comment by 46dude** [comment]
Ok no help or any interest on this. Thanks anyway.

**Comment by AnoRebel** [comment]
I have the same problem, did you find any solution?

**Comment by 46dude** [comment]
No but this was long ago so maybe now it may compile.

**Comment by AnoRebel** [comment]
> No but this was long ago so maybe now it may compile.
> 
> El vie., 3 jul. 2020 10:22, Ano Rebel <notifications@github.com> escribió:
> 

I just told you i got the same problem, so no, even now its not compiling, I'm on the latest Linux Mint (20)..
I guess i'll have to stick with the prebuilt package then.. 😒
