### ISSUE TITLE
draw gnome-pie on top of fullscreen windows

### ISSUE THREAD

**Issue by corebots** [Simmesimme/Gnome-Pie#169]
Is there an easy way to let gnome-pie appear when in fullscreen mode? while coding with my text editor fullscreen it looks like gnome-pie gets triggered when I press a shortcut but as if it would be hidden under the fullscreen window, seems like a bug. Great app btw, looking forward to openPie :)

**Comment by Simmesimme** [comment]
Should be fixed in develop!

**Comment by corebots** [comment]
thanks!
