### ISSUE TITLE
Change font of Gnome-Pie?

### ISSUE THREAD

**Issue by arcunofox** [Simmesimme/Gnome-Pie#174]
Hello! Basically the title. Gnome-Pie is great but I dislike the font of the text in the middle, and would like to replace it. However, in the settings I can't seem to find a settings for font. help?

**Comment by Simmesimme** [comment]
Hi there! The font depends on the theme you are using. So you either have to [choose a different theme](https://simmesimme.github.io/gnome-pie-themes.html) or modify the theme you are currently using. There is some information on the [theme format available](https://simmesimme.github.io/lessons/2015/04/26/themes-for-gnome-pie).

The easiest way is to export your current theme, modify the font and import it under a different name.
