### ISSUE TITLE
Can't Uninstall after Make Install

### ISSUE THREAD

**Issue by Michael-Obele** [Simmesimme/Gnome-Pie#198]
After installing by ./gnome-pie and cd build && sudo make install

When I needed to remove the app with 'sudo apt-get remove gnome-pie' or 'sudo apt-get remove --auto-remove gnome-pie' it didn't work.
Result:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'gnome-pie' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

with sudo apt-get remove Gnome-Pie
Result:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package Gnome-Pie

The file, folder and the app exist.

How can I uninstall the app?

**Comment by Schneegans** [comment]
If you haven't installed gnome-pie with you package manager, you'll not be able to uninstall it with the package manager. You can try `cd build && sudo make uninstall`.

**Comment by Michael-Obele** [comment]
Thank you. Done!
