### ISSUE TITLE
Shutdown and Reboot

### ISSUE THREAD

**Issue by gracca** [Simmesimme/Gnome-Pie#39]
Shutdown and Reboot don't work in Fedora 16:

german@centauri ~ $ gnome-pie 
[17:44:30:458796 MESSAGE] Started happily...
Error org.freedesktop.DBus.Error.UnknownMethod: Method "RequestShutdown" with signature "" on interface "org.gnome.SessionManager" doesn't exist

Error org.freedesktop.DBus.Error.UnknownMethod: Method "RequestReboot" with signature "" on interface "org.gnome.SessionManager" doesn't exist

This is a great application! Keep up your good work!
Germán.

**Comment by Simmesimme** [comment]
I know that this is an old issue... but maybe it got fixed after bcba017265153ce8e036e85750f76599c8fe23ff ... can you test this? Or are you not using Fedora anymore?

**Comment by Simmesimme** [comment]
Please re-open if that's still an issue!
