### ISSUE TITLE
Gnome-Pie crashes while trying to change icons 

### ISSUE THREAD

**Issue by zirco** [Simmesimme/Gnome-Pie#48]
I use gnome-pie for the beginning, and i think is a very useful tool,but i have the same issue from the first version. Every time that i try to change an icon for a pie o for a slice gnome-pie crash.

This is the Terminal output:

zirico@Desktop:~$ gnome-pie 
[MESSAGE] Welcome to Gnome-Pie 0.5.1!
[MESSAGE] Loading Pies from "/home/zirico/.config/gnome-pie/pies.conf".
[WARNING] Error when getting information for file '/media/8C4D-8602': No such file or directory
[WARNING] Icon "window-manager" not found! Using default icon...
[MESSAGE] Started happily...
[WARNING] Icon "window-manager" not found! Using default icon...
GLib (gthread-posix.c): Unexpected error from C library during 'Invalid argument': pthread_setspecific.  Aborting.
Aborted

My OS is ubuntu 11.10 . Thank you for the attention

**Comment by Simmesimme** [comment]
Is that still an issue? Else I will close this one...
