### ISSUE TITLE
Windows Key/MOD4/SUPER key does not launch pies

### ISSUE THREAD

**Issue by evilsoup** [Simmesimme/Gnome-Pie#50]
When creating a keybinding within gnome-pie using the Windows key, it simply doesn't work. 

For example, to launch the 'Applications' pie I tried binding 'windows-key+A', but that does nothing. When I run gnome-pie from a terminal, pressing that key combination has no effect whatsoever - it doesn't even generate an error.

Oddly, 'windows-key+right-click' works perfectly.

Oh, and when I set the 'WIN+A' binding in the gnome-pie settings, it records it as ''Mod4+Super+A'; not sure how relevant that is..

**Comment by Simmesimme** [comment]
That should actually work in the current version. If not, please re-open!

**Comment by Hebgbs** [comment]
Necro post, but topical;

Couldn't we use the super key _by itself?_ For people coming from mate-menu or brisk-menu, it would be more familiar than using a keybind which might already be bound to something for their compositor or some other application.
