### ISSUE TITLE
Gnome-Pie crashes while opening General Settings

### ISSUE THREAD

**Issue by renodesper** [Simmesimme/Gnome-Pie#51]
I tried to install gnome-pie in Archlinux, but when I tried to go to General Settings it just close itself.

Here is the output:

9:08:12 >> % @ ~
>> gnome-pie
[MESSAGE] Welcome to Gnome-Pie 0.5.2!
[MESSAGE] Loading Pies from "/home/renodesper/.config/gnome-pie/pies.conf".
[WARNING] Icon "gnome-pie" not found! Using default icon...
[MESSAGE] Started happily...
Assertion 'pthread_setspecific(t->key, userdata) == 0' failed at pulsecore/thread-posix.c:247, function pa_tls_set(). Aborting.
zsh: abort      gnome-pie

**Comment by Simmesimme** [comment]
I will close this (old) issue. Please re-open if it still occurs!
