### ISSUE TITLE
blank tray icon

### ISSUE THREAD

**Issue by mattia-b89** [Simmesimme/Gnome-Pie#58]
using gnome-pie (git or stable)
i can't get the icon on tray. not finding it, the system use blank icon.
a screenshot: http://imageshack.us/photo/my-images/171/screenshotfrom201206152.png/

i'm on archlinux 64bit + openbox
installed through AUR

**Comment by Simmesimme** [comment]
Is this still an issue? Else I'll close this issue...

**Comment by mattia-b89** [comment]
no, at least the icon properly appears in xfce tray are
you can close it!
