### ISSUE TITLE
Segmentation fault due to missing menu

### ISSUE THREAD

**Issue by justinallenreeves** [Simmesimme/Gnome-Pie#59]
As I don't run and lack most of Gnome 3 on my system, my usage is probably off label.  However I got it working easily and then not working after some effort.

$ gnome-pie
[MESSAGE] Welcome to Gnome-Pie 0.5.3!
[MESSAGE] Loading Pies from "/home/mute/.config/gnome-pie/pies.conf".
[WARNING] Failed to look up menu_file for "applications.menu"
[MESSAGE] Started happily...
Segmentation fault

I probably don't have whatever menu it's looking for if it's Gnome generated, but I'm not even certain if that's at fault or perhaps a library that got changed on Debian Wheezy in the last week.

**Comment by Elbullazul** [comment]
I have version 0.6.8 and still get this issue

Lubuntu 16.04
