### ISSUE TITLE
improovements to application switcher

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [Simmesimme/Gnome-Pie#61]
Hi there

i still love gnomepie since the first days. but since i use my working desktop with linux a lot more intense than back those days i would like to see a new feature.

im heavly using the different spaces on my ubuntu box and often a have up to 30 or 40 different apps running ... which brings the problem, that the applicationswitcher gets kinda huge! ;)
so would it be possible to add a new switcher with the following behavoir:
- the standard switcher with alt+^ shows me all open apps.
- the new - for example firing with alt+shit+^ - shows me only the apps on my current space
- the old one could get an option to "group" the applications according to the spaces. for example if you have  4 spaces and the first one holds 3 browser, the second one is empty and the third have 4 xterms and the last one got 1 editor the circle should be subdivided into 4 quartes and the icons should only arrange accordingly to the quarter which the icon belongs to! ;)

this would be AWEsome ;)

**Comment by ronaldoeyeem** [comment]
:+1:  for that. App switcher for the whole user or just the current workspace would be great.

**Comment by Simmesimme** [comment]
Most of this is actually implemented already :)
