### ISSUE TITLE
No Transparency

### ISSUE THREAD

**Issue by fjnalta** [Simmesimme/Gnome-Pie#72]
Hi i using arch with gnome 3.10. I would love to use gnome-pie but the menu is not transparent. It shows a black square as background.

I installed gnomepie from aur and compiled it by myself. Both dont work. I can't find any errors in logs.

I think the problem is, that the bg.svg is not shown transparent. But i could not fix it.

any suggestions?

**Comment by Simmesimme** [comment]
Hi! This should be fixed  6d9b7ba. I'll update the master branch soon!
