### ISSUE TITLE
Option to defer keyboard hotkey application

### ISSUE THREAD

**Issue by 0ion9** [Simmesimme/Gnome-Pie#74]
Because Gnome-Pie normally steals the input focus, the 'Simulate hotkey' action is much less useful than it could be; It basically can only trigger WM hotkeys.

With an option to delay the hotkey simulation until the Gnome-Pie display is destroyed, the 'hotkey' command could be used to interact with apps as well.

**Comment by Simmesimme** [comment]
The hotkey is actually triuggered when the input is not stolen anymore. For me it works as supposed (e.g. assign Ctrl-C to a slice -> it will copy your current selection).

What window manager are you using?

**Comment by 0ion9** [comment]
[AwesomeWM](http://awesome.naquadah.org/)
I've just verified that it still doesn't work, first by trying 'ctrl+shift+c' to copy text in the terminal, then trying 'super+6' (shows up as mod4+6) to switch to tag 6. Neither of these actions had any effect.

**Comment by aliichwan** [comment]
can only use super hotkey ? not combine

**Comment by Simmesimme** [comment]
Please re-open if that's still an issue!
