### ISSUE TITLE
Feature request : click on icons to execute action

### ISSUE THREAD

**Issue by aurelien35** [Simmesimme/Gnome-Pie#76]
Hi, I love gnome-pie, but I've seen a lot of newbie having problem using it : they all try to : 
- click on an icon to execute the action (this actually works, of course !)
- click elsewhere to close. Nobody think to click on the center. Of course, this leads to "WTF ? Why the window open it self ?" reactions, because the highligted action was executed.

So I think a good option should be a boolean to change this : 
- false (default) => act as in current version
- true => user must click on an icon to launch the action, any other click will close the app

**Comment by Simmesimme** [comment]
This feature is implemented in 2e8b0627b0975d4e5d35e5371747c56e670faf6d and will be released with the next version!
