### ISSUE TITLE
gnome-pie depends on libgee2 which is deprecated

### ISSUE THREAD

**Issue by JoergFF** [Simmesimme/Gnome-Pie#77]
Hello,

in debian libgee with the API 0.6 (1.0) is deprecated[1]. With the API 0.8 I get some errors:

[quote]
dh build --buildsystem=cmake
   dh_testdir -O--buildsystem=cmake
   dh_auto_configure -O--buildsystem=cmake
-- The C compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found Vala: /usr/bin/valac  
-- checking for a minimum Vala version of 0.11.0
--   found Vala, version 0.24.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'gtk+-3.0'
--   found gtk+-3.0, version 3.12.2
-- checking for module 'appindicator3-0.1'
--   package 'appindicator3-0.1' not found
-- checking for module 'unique-3.0'
--   found unique-3.0, version 3.0.2
-- checking for module 'libwnck-3.0'
--   found libwnck-3.0, version 3.4.7
-- checking for module 'libbamf3'
--   found libbamf3, version 0.2.118
-- checking for module 'gio-unix-2.0'
--   found gio-unix-2.0, version 2.40.0
-- checking for module 'cairo'
--   found cairo, version 1.12.16
-- checking for module 'gee-1.0'
--   package 'gee-1.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:279 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:46 (pkg_check_modules)
[/quote]

If you need help for this ask me.

CU
Jörg

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753863

**Comment by Simmesimme** [comment]
Fixed in 98344b3dba153db64fecc5e838e6319edeb1797c. Thanks for pointing to the issue! If a problem remains, please re-open!
