### ISSUE TITLE
Add missing keyword entry to desktop file

### ISSUE THREAD

**Issue by JoergFF** [Simmesimme/Gnome-Pie#78]
Hello,

I have added a patch for the missing keyword entry in the gnome-pie.desktop file:

Description: Add missing Keyword entry to desktop file
Author: Jörg Frings-Fürst
Forwarded:
Last-Update: 2015-01-15
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
Index: trunk/resources/gnome-pie.desktop
===================================================================
--- trunk.orig/resources/gnome-pie.desktop
+++ trunk/resources/gnome-pie.desktop
@@ -5,3 +5,4 @@ Comment=Cakes don't lie.
 Exec=gnome-pie
 Icon=gnome-pie
 Categories=GNOME;Utility;
+Keywords=Utility;Menu;

**Comment by Simmesimme** [comment]
Thank you for the patch! Committed in 2b20190ea01850cf24c45fc76450a49d12621acd.
