### ISSUE TITLE
gnome-pie depends on the deprecated libunique

### ISSUE THREAD

**Issue by ebassi** [Simmesimme/Gnome-Pie#79]
libunique has been deprecated for the past 4 years, since the introduction of the `GApplication` class, and its GTK+ sub-class, `GtkApplication`.

libunique is not maintained any more upstream, and its use in newly written code is highly discouraged.

(I am the author and former maintainer of libunique)

**Comment by Simmesimme** [comment]
Fixed in 6573fc7ce4da79986ad69e004316133409c3163c. Thanks for pointing out the issue!
