### ISSUE TITLE
not working on ubuntu-gnome 14.10

### ISSUE THREAD

**Issue by JulioOrdonezV** [Simmesimme/Gnome-Pie#97]
I got the following error trying to run the application installed from the PPA

[WARNING] Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gtk.Actions' on object at path /org/gnome/gnomepie

application fails to launch

**Comment by JulioOrdonezV** [comment]
built from source, same issue

**Comment by Simmesimme** [comment]
I have tested Gnome-Pie with a fresh installation of Ubuntu Gnome 14.10 (64 bit) in a virtual machine. Everything works as supposed. Did you install a newer version of gnome than the default?

Maybe you can try the workaround mentioned in the last comments in this bug report: https://bugs.launchpad.net/ubuntu/+source/at-spi2-core/+bug/1193236

**Comment by JulioOrdonezV** [comment]
Sorry, rebooted and I was able to run it... :)
