### ISSUE TITLE
Change workspace when selecting window on different workspace than current

### ISSUE THREAD

**Issue by leousa** [Simmesimme/Gnome-Pie#99]
This is perhaps a feature request that comes from issue #98. On selecting slice to bring focus on open window, it would be great to change workspace if window selected is in a different workspace than current.

**Comment by ronaldoeyeem** [comment]
leaving a comment to get notified.
If the devs go ahead with this feature I'll be happy to test.

**Comment by Simmesimme** [comment]
I'll try to fix this one. It's actually only not working in Unity. With Gnome and Elementary OS everything works as supposed...

**Comment by gabdub** [comment]
Actually, it works in Unity (14.04.2 / 64 bits) IF the current desktop doesn't have any window open or all windows in the current desktop are minimized. In this case, it changes to the selected window desktop properly. But when you are in a desktop with some visible window, it doesn't work.
--
from: http://www.valadoc.org/#!api=libwnck-3.0/Wnck.Workspace.activate
"The window manager may decide to refuse the request (to not steal the focus if there is a more recent user activity, for example)."

**Comment by gabdub** [comment]
I added some prints to "action.activated.connect()" in windowListGroup.vala and found that
`win.get_workspace().activate(time_stamp)` is NEVER called because all returned workspace seems to point to the same object!
`win.get_workspace().get_number()` always return 0!
`win.get_screen().get_active_workspace().get_number()` always return 0!
same for `get_layout_column() / get_layout_row()`!
get_viewport_x()/y() works only for the screen...
It's really strange....

**Comment by Simmesimme** [comment]
Jep, I saw this too. What does it mean? Is there a bug in Wnck? Are the Unity workspaces no "real" workspaces?

From the Wnck manual (https://developer.gnome.org/libwnck/stable/getting-started.html):

At its creation, a WnckScreen object will not have fetched information from the X server. If queried immediately after its creation (via wnck_screen_get_windows() or wnck_screen_get_workspaces(), for example), the WnckScreen object will look like there are no workspaces nor windows on the screen. This information is fetched in the main event loop with an idle source, to avoid an expensive synchronous operation on startup. If no main event loop is used, or if the information is needed as soon as possible after the creation of the object, wnck_screen_force_update() can be used to explicitly fetch the information.

But I think we are doing everything right here...

**Comment by gabdub** [comment]
I downloaded the Unity source code and the problem seems to be that Unity use "viewports" instead of "workspaces" (to easy animate the transition between desktops, I think).
I will try the function `win.is_in_viewport(workspace)` and see how to change the current viewport.
